### ISSUE TITLE
Ambiguity when granting scopes

### ISSUE THREAD

**Issue by tombowers** [openiddict/openiddict-core#1127]
I don't know if this is a question or a bug report. Forgive me! As I understand it, there are 2 types of scopes that can be granted in OIDC. "Protocol" scopes, which have side effects, such as `openid` which causes the ID token to be generated, and custom scopes, which when granted are simply returned as part of the scope claim.

In OpenIddict, we add scopes to the claims principal within the context to indicate which protocol and custom scopes to grant.

I also understand that OpenIddict uses a private claim type, 'oi_scp' to maintain an internal record of granted scopes, and when using the built-in extension methods for adding scopes, it is this private type which is added. This private type is also used in various places within the OpenIddict handlers to decide what to output.

The logic at https://github.com/openiddict/openiddict-core/blob/dev/src/OpenIddict.Server/OpenIddictServerHandlers.cs#L651 pushes the public scope claim into the private one as a sort of fallback, but this does not make the protocol scopes work (is it too late in the pipeline? i.e. have the private scopes already been evaluated?) This means there are 2 ways to grant custom scopes (use either `scope` or `oi_scp`), but only one way to grant protocol scopes (`oi_scp`).

I can just use the `oi_scp` claim type as this works for everything, but I'm currently doing so from a core project that shouldn't be aware of OpenIddict. I'm also acutely aware that this seems internal to OpenIddict, so I shouldn't really be using it directly. If the intent is to only ever use the private `oi_scp` claim, I will refactor to set scopes from an OpenIddict-specific project and use the built-in extension methods instead. If this is the case, can you clarify why the fallback option of using the standard scope claim is there at all? I want to be sure I'm using the library correctly.

I've added a minimal repro repo with some integration tests demonstrating the behaviour I'm seeing. https://github.com/tombowers/openiddict-tests

**Comment by kevinchalet** [comment]
> As I understand it, there are 2 types of scopes that can be granted in OIDC. "Protocol" scopes, which have side effects, such as openid which causes the ID token to be generated, and custom scopes, which when granted are simply returned as part of the scope claim.

That's right. And as you figured out, scopes are always granted the same way in OpenIddict, whether they are "protocol" or "custom" scopes.

> The logic at https://github.com/openiddict/openiddict-core/blob/dev/src/OpenIddict.Server/OpenIddictServerHandlers.cs#L651 pushes the public scope claim into the private one as a sort of fallback, but this does not make the protocol scopes work (is it too late in the pipeline? i.e. have the private scopes already been evaluated?) This means there are 2 ways to grant custom scopes (use either scope or oi_scp), but only one way to grant protocol scopes (oi_scp).

The handler you linked targets the `ProcessAuthenticationContext` event, which means it is only invoked when validating an incoming access/identity/refresh token or device/user/authorization code ; i.e it is never used when preparing an authorization or token response, which is why it has no effect when creating new tokens.

> If this is the case, can you clarify why the fallback option of using the standard scope claim is there at all? I want to be sure I'm using the library correctly.

The fallback/mapping mechanism has two purposes:

  - Ensuring OpenIddict 3.0 is able to validate ASP.NET Core Data Protection and JWT tokens/codes issued by previous versions of OpenIddict, where things were represented differently (in DP tokens, scopes were stored in `AuthenticationProperties`, in JWT tokens, as public `scope` claims).

  - For optimization reasons, access tokens produced by OpenIddict 3.0 don't include `oi_scp` claims: scopes are represented using the now-standard `scope` claim and dynamically mapped to `oi_scp` when validating access tokens.

This mechanism is unidirectional: when handling authorization/token requests, you have to use the OpenIddict scope claims (manually or using the `SetScopes` extension) to represent the granted scopes.

In .NET APIs, using `GetScopes` is also recommended, as it uses the OpenIddict scope claims, that have a more efficient representation (you don't have to split the standard `scope` claim). Like the server stack, the validation stack also includes a unidirectional mapping to map older representations to the new OpenIddict claims.

Hope it will be clear 😄

**Comment by kevinchalet** [comment]
> This means there are 2 ways to grant custom scopes (use either scope or oi_scp), but only one way to grant protocol scopes (oi_scp).

It's actually simpler than that: the only way to grant scopes - protocol or custom - is to use the OpenIddict scope claims (`oi_scp`).

Don't be fooled by the fact OpenIddict automatically grants the `openid` when 1) it's requested 2) the developer didn't call `SetScopes`. It's meant to allow returning identity tokens even if the developer doesn't want to bother with scopes.

This mechanism is handled by the `AttachDefaultScopes` handler:

https://github.com/openiddict/openiddict-core/blob/2786ac3c111673cca4c6c6f153780482d7252e77/src/OpenIddict.Server/OpenIddictServerHandlers.cs#L1465-L1500

**Comment by tombowers** [comment]
Thanks so much for the explanation. That's very clear now. Much appreciated!

**Comment by kevinchalet** [comment]
My pleasure. If you like the project, please consider encouraging your employer to sponsor the project: https://github.com/sponsors/kevinchalet ❤️
