### ISSUE TITLE
Create an example for managing authentication between multiple microservices using code flow and HttpClient

### ISSUE THREAD

**Issue by mxsoftware** [openiddict/openiddict-core#1181]
Hello, I have created microservices that make asp net core sites available and that use OpenIddict with code flow mode for authentication.
Through the browser, the passage from one site to another works correctly and no credentials are required between the communication between one site and another.
I have made several attempts to connect between microservices via Httpclient, but without success. Is it possible to have an example?

### To reproduce

Create a microservice for authentication in code flow mode and 2 microservices that communicate with each other using the code flow. Create an instance of Httpclient and make a request between one microservice and another

### Further technical details
- ASP.NET Core version: 3.1
- Visual Studio 2019 in Windows

**Comment by kinosang** [comment]
https://lmgtfy.app/?q=c%23+httpclient+bearer+token+example

It's not a `bug`

**Comment by kevinchalet** [comment]
Hi,

@kinosang is right, it's definitely not a bug.

![image](https://user-images.githubusercontent.com/6998306/99829612-cf4f5300-2b5c-11eb-843b-d6b365965c0a.png)

As mentioned, the ability to post questions on GitHub is reserved to sponsors as a way to thank them. If you need help or support, please consider [sponsoring the project](https://github.com/sponsors/kevinchalet). Otherwise, post your question on StackOverflow.

Thanks.
