### ISSUE TITLE
How to go about implementing purely as an API?

### ISSUE THREAD

**Issue by mkelley82** [openiddict/openiddict-core#120]
Is there an example somewhere how to implement openiddict purely as part of an API? So that users can be registered, etc... from say an Angular/Vue client? And then access to the API is regulated by openiddict?

**Comment by kevinchalet** [comment]
> Is there an example somewhere how to implement openiddict as part of an API?

We don't have a specific example yet, but this blog post might help you: http://capesean.co.za/blog/asp-net-5-jwt-tokens/

> So that users can be registered, etc...

FYI, OpenIddict is not directly responsible of registration, since it's handled by Identity (via `AccountController`), so you're totally free to implement it using an API controller.

**Comment by kevinchalet** [comment]
FYI, @KerryRitter posted a great blog post demonstrating how you roll your own `AccountController` to register a user with a simple API call: http://kerryritter.com/authorizing-your-net-core-mvc6-api-requests-with-openiddict-and-identity/
