### ISSUE TITLE
Update GetAsync()'s nullability context to declare TResult as nullable

### ISSUE THREAD

**Issue by kevinchalet** [openiddict/openiddict-core#1244]
The `GetAsync()` methods accepting a `query` parameter exposed by the stores/managers don't declare `TResult` as nullable:

https://github.com/openiddict/openiddict-core/blob/44fe717204be6d94fa114e64e79970b09564a4f4/src/OpenIddict.Abstractions/Stores/IOpenIddictApplicationStore.cs#L100-L114

Yet, all the implementations - EF 6, EF Core, MongoDB - use `FirstOrDefaultAsync()`, that may return null when no matching result could be found in the database (if the result type is not a value type).

We should fix the nullable annotations to make clearer that a null value can be returned. Doing that is not a binary breaking change but a potential source breaking change that may trigger an error in apps using nullable annotations and treating warnings as errors. That said, it's unlikely these methods - that require native `IQueryable` support in the underlying store provider - are widely used. We should determine whether we want to do that as part of 3.1.0 or if it must wait 4.0.0.

OrchardCore doesn't use nullable annotations so it won't be affected, but custom stores like the ones written by @panoukos41 will need a tiny change to avoid a C# warning. @panoukos41 don't hesitate to share your thoughts regarding this change! 😃

**Comment by panoukos41** [comment]
I like it, I am all in for nullable from the day I learned about it 😄 and it makes sense to me in such scenarios.

I don't know if these errors would be hard to tackle but I do see the 4.0.0 as the best option just to be safe. Since 4.0.0 means breaking changes might exist.

I think my implementation has reached its proper stage, the only thing I have my mind on is testing and I don't mind implementing such small changes 😃 when the time comes.

**Comment by kevinchalet** [comment]
@panoukos41 great, thanks for your feedback! 👍🏻
