### ISSUE TITLE
This server only accepts HTTPS requests - Using https connection

### ISSUE THREAD

**Issue by Gillardo** [openiddict/openiddict-core#1314]
I have uncommented the option `.DisableTransportSecurityRequirement()` and i have uploaded my code and loaded the site via https, but i am now getting this error message.

I am not sure how the code checks if its a secure connection or not?

Can see here the connection is to `/connect/token`
![image](https://user-images.githubusercontent.com/7406381/132194756-ab0902f3-b24c-489e-bd92-6a391bc81a42.png)

And it says its secure in host request
![image](https://user-images.githubusercontent.com/7406381/132194838-8970b43d-8618-4287-a15e-df121edff99c.png)

Not sure why this message would appear?

**Comment by kevinchalet** [comment]
Hi,

> I am not sure how the code checks if its a secure connection or not?

The handler `ValidateTransportSecurityRequirement` simply uses `HttpRequest.IsHttps`:

https://github.com/openiddict/openiddict-core/blob/16d4112589b23ec8d30562bb2c9671d8b7b67436/src/OpenIddict.Server.AspNetCore/OpenIddictServerAspNetCoreHandlers.cs#L283-L292

> Not sure why this message would appear?

Most likely because your application or an intermediate proxy between Internet and your app server is not correctly configured. Take a look at https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-5.0 for more information on how to fix that.

**Comment by Gillardo** [comment]
Thanks for the advice, this doesnt seem to help at the mo, but i think maybe its a server issue, so shall see what the server companies says, thanks for help

**Comment by kevinchalet** [comment]
Closing for now as there's not much OpenIddict can do to fix the issue you're seeing but if you need additional help, let me know.
