### ISSUE TITLE
Add Marten support

### ISSUE THREAD

**Issue by pixsperdavid** [openiddict/openiddict-core#1343]
I'm using OpenIddict on a project using Marten (https://martendb.io/) as a store.  For this I've written custom stores based on the existing MongoDB classes. If this would be of interest to add to the library I would be happy to format as a PR and submit.

**Comment by kevinchalet** [comment]
Thanks for your offer! Unfortunately, the demand for Marten support is so low - AFAIK, you're the first one asking for that - that I don't think maintaining stores for it in the long term would make sense.

That said, have you considered OSSing and maintaining Marten stores yourself? If you're interested, you can get some inspiration from https://github.com/panoukos41/couchdb-openiddict.

**Comment by pixsperdavid** [comment]
Fair enough, offer is there if you think this might be more viable in future (if there are more requests for this functionality). I'm unsure if I would have the time to appropriately maintain an independent repo for this but I will consider.

**Comment by Ankurkh1** [comment]
@pixsperdavid I would encourage you to OSSing MartenDB store. We are using MartenDB as our ORM and plan to use OpenIDDict very soon. 
@kevinchalet May be you can consider a separate repo for all stores. Something like logging framework do with sinks. Add a little official/Unofficial tag in front of it to let everyone know its support status.
I know its easier said than done. Just some food for thought :)

**Comment by kevinchalet** [comment]
> @kevinchalet May be you can consider a separate repo for all stores. Something like logging framework do with sinks. Add a little official/Unofficial tag in front of it to let everyone know its support status.

The README file mentions third-party projects, including stores for CouchDB developed by Panos Athanasiou: https://github.com/panoukos41/couchdb-openiddict

Adding a separate repository for stores that are not provided OOTB is certainly an option, but it's still code that will have to be maintained in the long term by someone and since I haven't seen anyone interested, it's something I'd need to maintain myself 😃 

I can't deny there's a real demand for additional stores (e.g Marten, RavenDB, Dapper, etc.) and additional features in general (e.g key management, Azure Functions or AWS Lambda support), but I have limited time to dedicate to OpenIddict. Of course, I'd like to spend much more time on it and joining the GitHub Sponsors program was supposed to help with that. While more than 20 individuals decided to sponsor the project - which is great - companies didn't and the truth is it's not sustainable. For full transparency, here's what I'm currently earning thanks to sponsors:

![image](https://user-images.githubusercontent.com/6998306/148100474-1a37ea08-77da-492a-ba3c-e477d355fb3d.png)

Of course:
  - The dollar/euro conversion has variable rates/fees that reduce the total.
  - As an independent worker, I pay roughly ~23% of professional taxes on that amount.
  - As a French citizen, I also have to pay income taxes on everything I earn, that included 😃

It's also interesting to note that a single sponsor actually gives 1/3rd of this amount.

I'm currently evaluating various options that would help me spend more time on OpenIddict and provide the community with new features, like the Marten stores you're interested in. This includes:
  - Moving the entire OpenIddict project to a dual-licence model similar to what's been adopted by the IdentityServer folks to force profitable companies that rely on OpenIddict for their business to fund it.
  - Keeping the existing core stack free but introducing new sponsors-only/paid projects. This could materialize as a "pro" offer, that could include stores and advanced features that wouldn't be part of the core.

I'm planning to create a blog post/GitHub thread to discuss these options with the OpenIddict community but I expect these options to be quite unpopular, so I need to be very careful and evaluate the pros of cons of each option.

**Comment by pablopioli** [comment]
> Fair enough, offer is there if you think this might be more viable in future (if there are more requests for this functionality). I'm unsure if I would have the time to appropriately maintain an independent repo for this but I will consider.

If you want to donate your code, I'm building a set of extensions to OpenIddict in 
https://github.com/pablopioli/Auth

A Marten store is in my plans but it would save me a lot of time existing working code. I have experience maintaining small libraries so I could take the responsability. If you are ok with this open an issue in my repo.

**Comment by kevinchalet** [comment]
@pablopioli if you're interested in seeing your repo listed in the OpenIddict documentation, please don't hesitate to send a PR to add it! 😃

**Comment by pablopioli** [comment]
Thanks @kevinchalet. I'm still learning a lot about OpenIddict, when I have something more polished I will.
