### ISSUE TITLE
What does a sliding expiration for refresh tokens actually do?

### ISSUE THREAD

**Issue by cryo75** [openiddict/openiddict-core#1644]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

4.x

### Question

The default expiration of refresh tokens is 14 days. What does the sliding expiration of refresh tokens mean? Or actually, How does `DisableSlidingRefreshTokenExpiration` affect refresh tokens?

Also, I noticed that the Velusia sample still uses `\connect\...` for the endpoints whilst the documentation for version 4 states what we should update the endpoints to `connnect\...`.

**Comment by kevinchalet** [comment]
> The default expiration of refresh tokens is 14 days. What does the sliding expiration of refresh tokens mean? Or actually, How does `DisableSlidingRefreshTokenExpiration` affect refresh tokens?

Sliding expiration means that each new refresh token is created with an expiration of `[issued date of the refresh token] + 14 days`. Concretely, if the client always retrieves a new refresh token before the last one expires, it can "indefinitely" get new tokens as long as it does so regularly. It's a very convenient feature as the user doesn't have to re-do an authorization dance for the client to keep working properly.

Disabling sliding expiration means all the refresh tokens are issued with the same exact/fixed expiration date: after 14 days, the user must re-do an authorization dance so that the client can get a new refresh token with a new expiration date.

> Also, I noticed that the Velusia sample still uses `\connect\...` for the endpoints whilst the documentation for version 4 states what we should update the endpoints to `connnect\...`.

Yeah, most of the samples haven't been updated to remove the leading slashes. None of them technically requires it as they don't use virtual paths, so `/connect` and `connect` point to the same address, but I opened https://github.com/openiddict/openiddict-samples/pull/227 to update them for consistency 😃 

Thanks.

**Comment by cryo75** [comment]
Thanks for the clarification.
