### ISSUE TITLE
Need an example of a .NET Standard 4.8 Owin Client working with a .NET7 OpenIdDict Server with custom DB

### ISSUE THREAD

**Issue by dlandi** [openiddict/openiddict-core#1648]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

4.x

### Question

Hello! Thanks for your work! 

I have been going through your samples; specifically **_Mortis_** (MVC/OWIn) and **_Velusia_** (Asp.NET.Core7).

I have a legacy Asp.NET 4.8 MVC app that I need to connect to the latest Asp.Net Core server on .NET 7.

I've looked through the samples, and one of the challenges is that they use the ASP.NET-provided integrations to Entity Framework via IdentityUser. But... these interfaces differ per .NET version, so the EF models differ. 

I want to unify the EF Models for both client and server so that I can use the same database for any client on coming from any version of .NET. 

Ideally, I would like to see an MVC/Owin client that is not tightly coupled to an ASP.NET EF provider to see how to connect the OWIN Client to a .NET7 Server. 

And, there must be a way to define EF Model classes that will work regardless of DotNet Version of Client Type. 

Looking forward to your thoughts.

**Comment by kevinchalet** [comment]
Hey @dlandi,

> Ideally, I would like to see an MVC/Owin client that is not tightly coupled to an ASP.NET EF provider to see how to connect the OWIN Client to a .NET7 Server.

The samples are not really "tightly coupled" to Identity or EF: they just happen to use them because they are the most common options (and for Identity, it's the only remaining viable option, given that MembershipReboot was deprecated in 2017).

OpenIddict is not tied to a particular membership provider as user authentication is always something you must implement yourself, using Identity, an external provider or a custom user authentication stack.

Regarding the Mortis sample:
  - The client doesn't reference Identity at all: the only sources of user details are the claims extracted from the tokens issued by the server.
  - The server uses Identity (legacy) but if you don't like it, you can replace the `AccountController` with your own stuff: none of that is specific to OpenIddict, it's just regular user authentication with cookies.

> And, there must be a way to define EF Model classes that will work regardless of DotNet Version of Client Type.

Not trivially: features have been added in ASP.NET Core Identity and the schema has changed to reflect that. Trying to share the same database with both ASP.NET Identity and ASP.NET Core Identity is going to be a very painful process and something I wouldn't recommend. That said, you should maybe ask the ASP.NET folks if they have a sample for this scenario.

Cheers.

**Comment by dlandi** [comment]
Ok. Let's say, I keep the Mortis (MVC/Owin) client and Velusia (Asp.NET.Core7) server as is. What do I need to integrate the Mortis Client with the Velusia server?

 So far, I have been unsuccessful.

**Comment by kevinchalet** [comment]
> I keep the Mortis (MVC/Owin) client and Velusia (Asp.NET.Core7) server as is. What do I need to integrate the Mortis Client with the Velusia server?

Nothing, except the URIs. I tested locally by changing the issuer address in the client sample (`Startup.cs` + the controller) and by adding a client registration in the Velusia sample for the Mortis client with the correct URIs and it worked just fine.

What error/symptom do you see?

**Comment by dlandi** [comment]
From our previous conversation:
![image](https://user-images.githubusercontent.com/3196088/213417282-5b8312f2-8b6a-4f01-8dc2-cefc55ee76a9.png)

Here are the changes I made, swapping the Mortis portNumber into the Velusia client setting for the "mvc"client and the Velusia port number into the issuer registration and controllers:

![image](https://user-images.githubusercontent.com/3196088/213417803-effe50f0-b3e5-47ee-83b3-9e0bd10816e6.png)

![image](https://user-images.githubusercontent.com/3196088/213417825-350a3559-03ee-4a21-aa58-6ab6b4d2795b.png)

I have tried running this several time on chrome and then on Microsoft Edge browser (with a clean cache) and I get this error message every time:

```
error:invalid_request
error_description:The specified 'redirect_uri' is not valid for this client application.
error_uri:https://documentation.openiddict.com/errors/ID2043
```

**Comment by dlandi** [comment]
OK. I googled for that openIddict issue, and I found a previous post where you suggested deleting the databases. I did that, and now it works.

I wonder what the underlying issue is here. Why would I need to delete the databases?

**Comment by Bartmax** [comment]
clients get added to database with it's configuration only if they doesn't exist. In your case looks, like you run the project (client created on db) then changed ports and since port doesn't match now you get a redirect_uri parameter that wasn't up to date, deleting the database makes the app recreate the client configuration with proper port on the correct redirect_uri.

**Comment by dlandi** [comment]
Thanks! Makes sense.

**Comment by kevinchalet** [comment]
I believe @Bartmax's explanation is exactly what happened.

Closing, but feel free to reopen if you need additional details 😃
