### ISSUE TITLE
Is there a sample on how to use the revocation endpoint?

### ISSUE THREAD

**Issue by cryo75** [openiddict/openiddict-core#1656]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

4.x

### Question

Is there a sample on how to use the revocation endpoint or is this endpoint implemented internally? How can native apps logout (or revoke tokens) without opening the browser?

**Comment by kevinchalet** [comment]
> Is there a sample on how to use the revocation endpoint or is this endpoint implemented internally?

As you correctly guessed, the endpoint is implemented internally, so revocation requests are handled by OpenIddict itself (assuming you enabled the endpoint in the server options, of course).

Since the implementation is standard, you just have to send the client credentials, the token to revoke - and optionally, a `token_type_hint` containing its type (e.g `refresh_token` or `access_token`) - to the revocation endpoint:

```http
POST /revoke HTTP/1.1
Host: server.example.com
Content-Type: application/x-www-form-urlencoded
Authorization: Basic czZCaGRSa3F0MzpnWDFmQmF0M2JW

token=45ghiukldjahdnhzdauz&token_type_hint=refresh_token
```

https://www.rfc-editor.org/rfc/rfc7009#section-2.1

Hope it helped 😃

**Comment by cryo75** [comment]
Thanks it helped!
