### ISSUE TITLE
ADFS on-premise

### ISSUE THREAD

**Issue by dmkk3r** [openiddict/openiddict-core#1664]
### Personal contribution

- [ ] I'm not interested in submitting a pull request and understand that this provider may not be implemented in the near future without my contribution.

### Provider name

ADFS

### Provider address

Depends on the ADFS on-premise installation

### Documentation page

https://learn.microsoft.com/de-de/windows-server/identity/ad-fs/development/ad-fs-openid-connect-oauth-concepts

### OpenID Connect discovery/OAuth 2.0 authorization server metadata support

- [ ] The provider doesn't support OpenID Connect discovery or OAuth 2.0 authorization server metadata and requires using static configuration.

### Authorization endpoint address (static configuration only)

/adfs/oauth2/authorize/

### Token endpoint address (static configuration only)

/adfs/oauth2/token/

### Userinfo endpoint address (static configuration only)

/adfs/userinfo

### Additional context

openid-configuration endpoint: /adfs/.well-known/openid-configuration

**Comment by kevinchalet** [comment]
Hey,

Assuming we don't want to support ADFS 3.0 since Windows Server 2012 is no longer officially supported (ADFS 3.0 was WS-Fed/OAuth 2.0-only), it should be very easy to implement.

Would you like to send a PR to add it to the list of supported providers? If so, please name it `ActiveDirectoryFederationServices` and don't use a static configuration (given that discovery is supported by ADFS 4.0).

**Comment by kevinchalet** [comment]
I went ahead and opened https://github.com/openiddict/openiddict-core/pull/1667. I tested it on Windows Server 2022 and had no issue.
