### ISSUE TITLE
Flow with EnableDegradedMode

### ISSUE THREAD

**Issue by AlexAlexGoTO** [openiddict/openiddict-core#1757]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

4.x

### Question

Hello @kevinchalet, I'm trying to use your package I need AuthorizationCodeFlow for OAuth in my WebApi so my client project should be able to receive Token and it works!
Can I ask maybe just for fast review of my configuration is there any security vulnerability or maybe it's totally incorrect. 
I used hardcoded ClientId, ClientSecret, RedirectUrl.
I'm doing almost nothing in those handlers but everything work, so because of that it looks suspicious for me and I decided to ask you if everything okay. Maybe I'll also add some scopes later.

`------
                               
            services.AddOpenIddict()
                    .AddServer(options =>
                    {      
                        options.AddDevelopmentEncryptionCertificate()
                               .AddDevelopmentSigningCertificate();    
                               
                        options.AllowAuthorizationCodeFlow();

                        options.SetAuthorizationEndpointUris("/connect/authorize")
                               .SetTokenEndpointUris("/connect/token");

                        options.EnableDegradedMode();

                        options.UseOwin()
                          .DisableTransportSecurityRequirement();

                        options.AddEncryptionKey(new SymmetricSecurityKey(Convert.FromBase64String("DRjd/GnduI3Efzen9V9BvbNUfc/VKgXltV7Kbk9sMkY=")));

                        options.AddEventHandler<ValidateAuthorizationRequestContext>(builder =>
                                builder.UseInlineHandler(context =>
                                {
                                    if (!string.Equals(context.ClientId, Customer.ClientId, StringComparison.Ordinal))
                                    {
                                        context.Reject(
                                            error: Errors.InvalidClient,
                                            description: "The specified 'client_id' doesn't match a registered application.");

                                        return default;
                                    }

                                    if (!string.Equals(context.Request.ClientSecret, Customer.ClientSecret, StringComparison.Ordinal))
                                    {
                                        context.Reject(
                                            error: Errors.InvalidClient,
                                            description: "The specified 'client_secret' doesn't match a registered application.");

                                        return default;
                                    }

                                    if (!string.Equals(context.RedirectUri, Customer.RedirectUri, StringComparison.Ordinal))
                                    {
                                        context.Reject(
                                            error: Errors.InvalidClient,
                                            description: "The specified 'redirect_uri' is not valid for this client application.");

                                        return default;
                                    }

                                    return default;
                                }));
                        options.AddEventHandler<ValidateTokenRequestContext>(builder =>
                                builder.UseInlineHandler(context =>
                                {
                                    if (!string.Equals(context.ClientId, Customer.ClientId, StringComparison.Ordinal))
                                    {
                                        context.Reject(
                                            error: Errors.InvalidClient,
                                            description: "The specified 'client_id' doesn't match a registered application.");

                                        return default;
                                    }

                                    if (!string.Equals(context.Request.ClientSecret, Customer.ClientSecret, StringComparison.Ordinal))
                                    {
                                        context.Reject(
                                            error: Errors.InvalidClient,
                                            description: "The specified 'client_secret' doesn't match a registered application.");

                                        return default;
                                    }

                                    return default;
                                }));

                        options.AddEventHandler<HandleAuthorizationRequestContext>(builder =>
                                builder.UseInlineHandler(async context =>
                                {
                                    await Task.Delay(1); 

                                    var identity = new ClaimsIdentity(TokenValidationParameters.DefaultAuthenticationType);

                                    identity.AddClaim(new Claim(Claims.Subject, Customer.ClientId));

                                    // Mark all the added claims as being allowed to be persisted in the access token,
                                    // so that the API controllers can retrieve them from the ClaimsPrincipal instance.
                                    foreach (var claim in identity.Claims)
                                    {
                                        claim.SetDestinations(Destinations.AccessToken);
                                    }

                                    // Attach the principal to the authorization context, so that an OpenID Connect response
                                    // with an authorization code can be generated by the OpenIddict server services.
                                    context.Principal = new ClaimsPrincipal(identity);
                                }));
                    })
                    .AddValidation(options =>
                    {
                        options.UseLocalServer();
                        options.UseOwin();
                    });`
UPD: Hmm or maybe I wrong and I just need ClientCredentials flow? Because my idea that in future I will have multiple clients and I will give them access to my API.

**Comment by kevinchalet** [comment]
Hey,

> Hello @kevinchalet, I'm trying to use your package I need AuthorizationCodeFlow for OAuth in my WebApi so my client project should be able to receive Token and it works!

Haha, it's always a good start when it works 😄 

> Can I ask maybe just for fast review of my configuration is there any security vulnerability or maybe it's totally incorrect.
I used hardcoded ClientId, ClientSecret, RedirectUrl.
I'm doing almost nothing in those handlers but everything work, so because of that it looks suspicious for me and I decided to ask you if everything okay. Maybe I'll also add some scopes later.

It's important to note that the degraded mode (that allows using OpenIddict in a basically stateless mode, i.e without a DB) disables security features like application permissions, token storage and token revocation (e.g there's no authorization code replay detection).

If you're not familiar with OAuth 2.0/OpenID Connect, I'd encourage you to use the normal mode with a backing DB. If you go that route, you'll be able to remove the `ValidateAuthorizationRequest`/`ValidateTokenRequest` handlers as the client credentials/`redirect_uri` will be validated for you by OpenIddict when using the normal mode.

If you still want to use the degraded mode, I'd suggest making a couple of changes:
  - Remove the `client_secret` validation from your `ValidateAuthorizationRequest` handler as there's no `client_secret` parameter in authorization requests.

  - Use a time-constant comparer to prevent statistical attacks when validating the client secret. Since you're using OpenIddict on OWIN/.NET Framework, you cannot directly use .NET Core's [CryptographicOperations.FixedTimeEquals](https://learn.microsoft.com/en-us/dotnet/api/system.security.cryptography.cryptographicoperations.fixedtimeequals) but you can copy its implementation to your project:

https://github.com/openiddict/openiddict-core/blob/28ec4293ef4f2d4f8090059553827567bba1ce12/shared/OpenIddict.Extensions/Helpers/OpenIddictHelpers.cs#L800-L843

Here's how to use it with `string` instances:

https://github.com/openiddict/openiddict-core/blob/479877cbf5f812e507b7cc53ef78cdcca16d43a4/src/OpenIddict.Server/OpenIddictServerHandlers.Exchange.cs#L1605-L1621

  - Remove `await Task.Delay(1);` that will unnecessarily slow down the authorization request handling.

> UPD: Hmm or maybe I wrong and I just need ClientCredentials flow? Because my idea that in future I will have multiple clients and I will give them access to my API.

You didn't describe your scenario, so it's impossible to say whether you're using the right flow or not but:
  - The authorization code flow always involves a user who needs to authenticate (and optionally approve the demand, depending on whether you implement a consent screen or not).
  - The client credentials flow is for machine-to-machine/API-to-API scenarios where there's no user involved.

Hope it helped.

**Comment by AlexAlexGoTO** [comment]
Thanks a lot for your advices. 
I decided that I'm okay with machine-2-machine for now. 
I think I will stay in degrade mode, don't want to add something external to my DB and I can't use inmemory because maybe in future I'll have multiple instances so I'll need to sync those in memory storages.
It's really nice that you told me about those **time-constant comparer**, good information. 
I'll finish everything next week, maybe ask you something else if I get stuck.
One more time - Thanks a lot! :)

**Comment by kevinchalet** [comment]
> One more time - Thanks a lot! :)

My pleasure! Thanks for sponsoring the project 😃

**Comment by AlexAlexGoTO** [comment]
Hi, @kevinchalet thank you for amazing work. I'm using ur library and everything work like a charm.

**Comment by kevinchalet** [comment]
@AlexAlexGoTO hey! Awesome, glad to hear that! ❤️
