### ISSUE TITLE
[Client] How to override interactive authentication logic?

### ISSUE THREAD

**Issue by xperiandri** [openiddict/openiddict-core#1775]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

4.x

### Question

We need to integrate OpenIddict Client into Unity 3D app and use:
1. WASM → popup browser window
		a. Unity calls JS script to open a popup window and passes request parameters
		b. JS script catches an auth code and passes it back to Unity (or passes error or window closed)
		c. Unity exchanges code for a token
2. UWP → preferably [Web Account Manager](https://learn.microsoft.com/en-us/windows/uwp/security/web-account-manager) or [Web authentication broker](https://learn.microsoft.com/en-us/windows/uwp/security/web-authentication-broker) with the same functionality as above

How to write sich plugins for OpenIddict Client?
Can you provide a sample or a project template that demonstrates that?

**Comment by kevinchalet** [comment]
> UWP → preferably [Web Account Manager](https://learn.microsoft.com/en-us/windows/uwp/security/web-account-manager) or [Web authentication broker](https://learn.microsoft.com/en-us/windows/uwp/security/web-authentication-broker) with the same functionality as above

WinRT's `WebAuthenticationBroker` is already fully supported by the new OpenIddict client system integration, but only in UWP apps: `WebAuthenticationBroker` is basically a legacy component that Microsoft no longer updates - it's still based on the IE rendering engine and thus is incompatible with many recent websites - and it doesn't work in WinUI 3.0 apps (see https://github.com/microsoft/WindowsAppSDK/issues/441 for more information).

While using it is not recommended in most cases, you can enable it in the system integration options so that calls to `AuthenticateInteractivelyAsync()` use `WebAuthenticationBroker` instead of launching the system browser:

```csharp
// Add the operating system integration.
options.UseSystemIntegration()
       .UseWebAuthenticationBroker();
```

> 1. WASM → popup browser window
>        a. Unity calls JS script to open a popup window and passes request parameters
>        b. JS script catches an auth code and passes it back to Unity (or passes error or window closed)
>        c. Unity exchanges code for a token

WASM is not yet supported by `OpenIddict.Client.SystemIntegration`. It's on my radar but the demand isn't very high ATM.

I'm not familiar with Unity 3D at all, but can't you just use the default system browser with either protocol activations (i.e custom URI schemes) or the embedded web server?

> How to write sich plugins for OpenIddict Client?

The events model is what you need as soon as you want to customize things to that degree.

> Can you provide a sample or a project template that demonstrates that?

There's no dedicated UWP sample as UWP is basically legacy and doesn't support SDK-style projects, but you can take a look at the `InvokeWebAuthenticationBroker` handler to see how it's implemented:

https://github.com/openiddict/openiddict-core/blob/627de0f66a577a8948e87d84ba61178330b986a3/src/OpenIddict.Client.SystemIntegration/OpenIddictClientSystemIntegrationHandlers.Authentication.cs#L47-L157

**Comment by xperiandri** [comment]
Looks good. This is what I was looking for.
I've just traced the `WebAuthenticationBroker` logic till here
https://github.com/openiddict/openiddict-core/blob/63fe12e8b149a2f9e0cb636beddc15bfc9936e3f/src/OpenIddict.Client.SystemIntegration/OpenIddictClientSystemIntegrationHandlers.cs#L212
where you put URI into `BaseUri`

Should we just put it there the same way and pipeline will handle authorization code automatically?

**Comment by kevinchalet** [comment]
> Should we just put it there the same way and pipeline will handle authorization code automatically?

Yeah, the authorization code redeeming/token validation will be handled for your by OpenIddict.

Note: in case this wasn't clear, for this to work, you need to trigger the `ProcessRequest(Context)` event at some point.
For `WebAuthenticationBroker`, it's directly done in the handler that triggers the challenge via `await _service.HandleWebAuthenticationResultAsync(result, context.CancellationToken);` as the result is immediately available but in other cases, it's done elsewhere. E.g, the embedded HTTP server does it here: 

https://github.com/openiddict/openiddict-core/blob/63fe12e8b149a2f9e0cb636beddc15bfc9936e3f/src/OpenIddict.Client.SystemIntegration/OpenIddictClientSystemIntegrationHttpListener.cs#L220-L233

https://github.com/openiddict/openiddict-core/blob/63fe12e8b149a2f9e0cb636beddc15bfc9936e3f/src/OpenIddict.Client.SystemIntegration/OpenIddictClientSystemIntegrationService.cs#L63-L64

https://github.com/openiddict/openiddict-core/blob/63fe12e8b149a2f9e0cb636beddc15bfc9936e3f/src/OpenIddict.Client.SystemIntegration/OpenIddictClientSystemIntegrationService.cs#L85-L138

**Comment by kevinchalet** [comment]
Doing some housecleaning, but feel free to reopen if necessary 😃

**Comment by xperiandri** [comment]
We have added the packages `OpenIddict.Client` and `OpenIddict.Client.SystemNetHttp` version `4.4.0` to a WASM project. And copied WPF code.
1. That code uses cryptography not supported on WASM.
2. Why to add development signing kwey if OpenIddict server returns keys.

So I suggested to just retrieve a configuration from `well-known`

But with the initialization code like this:
``` C#
builder.Services.AddOpenIddict()
    .AddClient(async options =>
    {
        options.AllowAuthorizationCodeFlow()
               .AllowRefreshTokenFlow();
    
        var key = await GetKeyFromWellKnownEndpoint();
        options.AddEncryptionKey(key);
        options.UseSystemNetHttp();
    
       var app = new OpenIddictClientRegistration
        {
            Issuer = new Uri("https://localhost:44395/, UriKind.Absolute),
            ProviderName = "Local",
            ClientId = "Unity",
            GrantTypes = { GrantTypes.AuthorizationCode, GrantTypes.RefreshToken },
            RedirectUri = new Uri("https://localhost:7131/login/local, UriKind.Absolute),
            PostLogoutRedirectUri = new Uri("https://localhost:7131/logout/local, UriKind.Absolute),
            Scopes = { Scopes.Email, Scopes.Profile, Scopes.OfflineAccess, "api" }
        };
        options.Configure(options =>
        {
            options.GrantTypes.Add(GrantTypes.AuthorizationCode);
            options.RedirectionEndpointUris.Add(new Uri("https://localhost:7131/callback/login/local, UriKind.Absolute));
            options.PostLogoutRedirectionEndpointUris.Add(new Uri("https://localhost:7131/callback/logout/local, UriKind.Absolute));
        });
        options.AddRegistration(app);
    });
```

However on call to `GetKeyFromWellKnownEndpoint()`, we still getting the error `"System.InvalidOperationException: The redirection endpoint must be enabled to use the authorization code and implicit flows" when calling `_service.GetServerConfigurationAsync("Local")`.`

`GetKeyFromWellKnownEndpoint()` just calls `GetConfigurationAsync` on configuration and extracts JWK.

Could you suggest what might be causing this error and how to resolve it?

Probably related to #1690

**Comment by kevinchalet** [comment]
> That code uses cryptography not supported on WASM.

If Unity 3D uses the same WASM .NET runtime as Blazor, it's not surprising: there are important limitations regarding crypto support in the current version (it should slowly improve). There isn't much OpenIddict can do here, as the limitations are in the .NET BCL (and as I said, OpenIddict on WASM is unsupported at the moment).

> Why to add development signing kwey if OpenIddict server returns keys.

The client keys are completely independent from the server keys, that are not used with the same types of tokens (client keys are used to protect the state tokens created by the OpenIddict client while the server keys are used to sign things like identity tokens). Trying to use a server key as a client key is a terrible idea (but luckily, it will never work, as you need the private part of the RSA key, which is never returned by the JWKS endpoint... and anyway RSA doesn't work on WASM).

> Could you suggest what might be causing this error and how to resolve it?

As I said, what you're trying to do is a terrible idea that will never work. That said, the specific issue you're seeing is likely caused by the illegal use of `async` here, that results in a race condition (the delegate is an `Action<OpenIddictClientBuilder>`, so it's never awaited).

Can't you use a regular .NET runtime for your Unity app?

**Comment by xperiandri** [comment]
Unity claims .NET Standard 2.1
So it should work.
What we tried to acomplish is a sample for Unity developer that opens a popup window via JS and does .NET to JS and back interop.
As working with Blazor much simpler than trying to embed JS into Unity and debug that.

**Comment by xperiandri** [comment]
Can we disable signing or set JWKs insted on WASM?

**Comment by kevinchalet** [comment]
> Unity claims .NET Standard 2.1
So it should work.

It doesn't mean these methods will work on all platforms. Many/most crypto APIs on WASM will throw a `PlatformNotSupportedException()` at runtime. It should get better in the next .NET version, tho'.

> What we tried to acomplish is a sample for Unity developer that opens a popup window via JS and does .NET to JS and back interop.

As I said, OpenIddict on WASM isn't yet supported (and it's even not going to be an easy task given that browser apps have a quite different execution model compared to desktop apps).

> As working with Blazor much simpler than trying to embed JS into Unity and debug that.

Blazor WASM isn't supported by `OpenIddict.Client.SystemIntegration`, but Blazor Hybrid is (I recently tested this scenario with a MAUI app on Windows and it worked fine).

> Can we disable signing or set JWKs insted on WASM?

Well, it's technically possible, but a bad idea given that it's an essential part of the security model.

If you told me more about your app, I could maybe suggest a few alternatives.

**Comment by xperiandri** [comment]
It is a Unity app that was previously built for native platfroms but now expected to be used as WebGL WebAssembly only version.
It either gets Teams token from Teams and exchanges it to OpenIddict token (implemented as you suggested)
or log in via OpenID Connect (here I wanted to do authorization code retrieving via JS by opening a popup window and passing that back to Unity on  WASM built from .NET and exchange code to token inside)

**Comment by kevinchalet** [comment]
I obviously don't recommend it, but you should be able to disable the identity token signature validation logic using IdentityModel's hooks:

```csharp
options.AddEventHandler<ValidateTokenContext>(builder =>
{
    builder.UseInlineHandler(context =>
    {
        if (context.ValidTokenTypes.Count is 1 && context.ValidTokenTypes.Contains(TokenTypeHints.IdToken))
        {
            context.TokenValidationParameters.ValidateIssuerSigningKey = false;
            context.TokenValidationParameters.SignatureValidator = (token, parameters) => new JsonWebToken(token);
        }

        return default;
    });

    builder.SetOrder(ResolveTokenValidationParameters.Descriptor.Order + 1);
});
```

Also, for the state tokens produced by the OpenIddict client, you'll likely need to switch from X.509 certificates with RSA keys to symmetric keys, as RSA isn't supported on WASM. Something like this:

```csharp
options.AddSigningKey(new SymmetricSecurityKey(RandomNumberGenerator.GetBytes(256 / 8)));
options.AddEncryptionKey(new SymmetricSecurityKey(RandomNumberGenerator.GetBytes(256 / 8)));
```

If it still doesn't work, consider using a JS OIDC library.
