### ISSUE TITLE
Using custom HTML or script Nonce support on authorize page

### ISSUE THREAD

**Issue by salihozkara** [openiddict/openiddict-core#1787]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Describe the solution you'd like

https://github.com/openiddict/openiddict-core/blob/778b5c81d991668c1d960f25672df9be6569c1ba/src/OpenIddict.Server.AspNetCore/OpenIddictServerAspNetCoreHandlers.Authentication.cs#L382-L386

When I open the nonce feature for scripts, I get an error because this is hard code. Can you make a development for custom HTML or script nonce here?

**Comment by kevinchalet** [comment]
> Can you make a development for custom HTML or script nonce here?

You can already override the existing `response_mode=form_post` response generation logic by removing the built-in `ProcessFormPostResponse` event handler (using `options.RemoveHandler(ProcessFormPostResponse.Descriptor)`) and replacing it by a custom handler that does what you want (@maliming is quite familiar with OpenIddict's events model).

Regarding your suggestion, updating the built-in handler to include a nonce attribute as part of the `<script>` tag would be quite tricky, as OpenIddict is not aware of the random nonce(s) generated by your CSP library.

Instead, you may want to consider using a SHA256 hash for the inline script used by OpenIddict. You can easily compute it using an online generator like https://csplite.com/csp/sha/?pl=eJxLtDK0qi62MrFS8gjx9VGyBjINrJRsipOLMgtK7FLyk0tzU%2FNK9NLyi3L1ikuTcjNLNDStbfSh8krWtQCkRxV0#result.

Alternatively, you could also disable CSP for the authorization endpoint URI so that no CSP header is added to the `response_mode=form_post` responses generated by OpenIddict.

Hope it helped 😃
