### ISSUE TITLE
Replace the default IMemory cache with IDistributedCache 

### ISSUE THREAD

**Issue by jacojvv-dev** [openiddict/openiddict-core#1797]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

4.x

### Question

Hi.

I am just curious about using IDistributedCache instead of IMemory cache for caching entities. Specifically I am looking to replace the in memory caching for the application manager to use Redis instead.

Currently I can't see a way of doing it without implementing my own manager, resolver and possibly cache.

Any guidance in this regard would be greatly appreciated!

Thanks again for all the work you put into this project!

**Comment by kevinchalet** [comment]
Hey,

> I am just curious about using IDistributedCache instead of IMemory cache for caching entities. Specifically I am looking to replace the in memory caching for the application manager to use Redis instead.

It's important to note that the in-memory cache you're referring to is actually quite specific and likely different from what you're expecting as it's actually always created per-scope: cached entities are not shared between multiple ASP.NET Core requests.

The reason it exists is due to how the OpenIddict client, server and validation stacks are designed: while they form a chained pipeline, all the event handlers that are responsible for the request processing are actually independent from each other. As a result, multiple handlers will always need to retrieve the same entity - e.g the client application - from the DB at different places in the pipeline: if we hit the DB each time a handler needed to resolve the same entity, that would be terrible from a performance perspective. The built-in scoped cache mitigates that by storing these entities in an in-memory cache so that all the handlers get the same instance.

(in a way, you can see that as an equivalent of NHibernate's first-level cache concept 😃)

If you wanted to implement a distributed cache working across multiple requests, custom stores would be the right place for that (no need for custom managers or resolvers).

> Thanks again for all the work you put into this project!

Thanks for your kind words! ❤️

**Comment by jacojvv-dev** [comment]
Thanks. That explanation makes a lot of sense to me. I was under the impression that the cache is shared between requests but come to think of it it makes sense that it is scoped to ensure the behavior above. (I was also wondering how that 250 default limit is not being hit across all the different requests - but - turns out I am just a little bit of an idiot and should spend more time reading the source before making assumptions 😄)

The issue I am trying to resolve is caching across several requests as you outlined above. Specifically the system where I introduced this where there are not many applications. Caching in a distributed manner will save several requests to the database between different .Net requests.

As for your opinion on the implementation would it be better to implement the store from scratch or inherit from the current .Net Core store and override by calling the base and caching in the distributed cache from there. Essentially just wrapping what Openiddict ships with with a little distributed cache layer on top.

Also - amazed with the fast response time here!

**Comment by kevinchalet** [comment]
> Thanks. That explanation makes a lot of sense to me. I was under the impression that the cache is shared between requests but come to think of it it makes sense that it is scoped to ensure the behavior above. (I was also wondering how that 250 default limit is not being hit across all the different requests - but - turns out I am just a little bit of an idiot and should spend more time reading the source before making assumptions 😄)

Hehe, you're not the first one tricked by the fact it's a per-scope cache 😄 

> As for your opinion on the implementation would it be better to implement the store from scratch or inherit from the current .Net Core store and override by calling the base and caching in the distributed cache from there. Essentially just wrapping what Openiddict ships with with a little distributed cache layer on top.

Technically, wrapping the existing EF 6/Core stores should be doable but it may be a bit tricky due to the fact EF's change tracker has some affinity.

If high performance is what you're looking for, I'd encourage you to create custom stores from scratch (for a SQL DB, you'll probably want to use Dapper... or ADO.NET directly if you're feeling brave :trollface:)

> Also - amazed with the fast response time here!

Thanks! Restricting the ability to request support to sponsors greatly helped with that. Thanks for sponsoring the project and making that possible! ❤️

**Comment by jacojvv-betsoftware** [comment]
Great. Thanks.

For now the performance of the database calls are not the most critical issue,  merely the volume.

What I will do is a tiered cache approach that is roughly based on what is implemented in the current stores so that I can take advantage of the memory for multiple calls into the same store within the same scope, but read the data from Redis where possible.

Beyond that I will look at using Dapper for hot paths after evaluating performance gained from the usage of cache. Don't want to do too much at once.

Thanks again for the guidance provided.

Cheers.

**Comment by jacojvv-dev** [comment]
Great. Thanks.

For now the performance of the database calls are not the most critical issue, merely the volume.

What I will do is a tiered cache approach that is roughly based on what is implemented in the current stores so that I can take advantage of the memory for multiple calls into the same store within the same scope, but read the data from Redis where possible.

Beyond that I will look at using Dapper for hot paths after evaluating performance gained from the usage of cache. Don't want to do too much at once.

Thanks again for the guidance provided.

Cheers.
