### ISSUE TITLE
Migration from OpenIddict 2.0 to 4.7

### ISSUE THREAD

**Issue by cc3241** [openiddict/openiddict-core#1864]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

4.x

### Question

Hi Kevin,

We are in the midst of migrating from OpenIddict 2.0 to v4.7. We've updated the old code with the new and a couple of things caught my eye. 

- We were using `AddEphemeralSigningKey()` in production 🤦🏻
- We were not using `UseDataProtection()`
- We were not rolling refresh tokens

I've got two questions:
1. Will these changes result in users having their tokens invalidated and being forced to login again as a result of the changed signing key?
2. I'm disabling rolling refresh tokens because the refresh tokens that the users have can be many months old. I would expect these refresh token to error out without adding `DisableRollingRefreshTokens()`. Is that assumption correct?

Old v2.0:
```csharp
services.AddOpenIddict()
    .AddCore(options =>
    {
      options.UseEntityFrameworkCore()
             .UseDbContext<ApplicationDbContext>();
    })
    .AddServer(options =>
    {
      options.UseMvc();

      options.EnableAuthorizationEndpoint("/connect/authorize")
             .EnableLogoutEndpoint("/connect/logout")
             .EnableTokenEndpoint("/connect/token")
             .EnableIntrospectionEndpoint("/connect/introspect")
             .EnableUserinfoEndpoint("/api/userinfo");

      options.AllowAuthorizationCodeFlow()
             .AllowPasswordFlow()
             .AllowRefreshTokenFlow();

      options.SetAccessTokenLifetime(TimeSpan.FromHours(1));
      options.SetRefreshTokenLifetime(TimeSpan.FromDays(30));

      options.RegisterScopes(OpenIddictConstants.Scopes.Email,
                             OpenIddictConstants.Scopes.Phone,
                             OpenIddictConstants.Scopes.Profile,
                             OpenIddictConstants.Scopes.Roles,
                             OpenIddictConstants.Scopes.OfflineAccess);

      options.EnableRequestCaching();

      options.AddEphemeralSigningKey();

      options.IgnoreEndpointPermissions()
             .IgnoreGrantTypePermissions()
             .IgnoreScopePermissions();
    })
    .AddValidation();
```

New v4.7:
```csharp
services.AddOpenIddict()
    .AddCore(options =>
    {
      options.UseEntityFrameworkCore()
               .UseDbContext<ApplicationDbContext>();

      options.UseQuartz();
    })
    .AddServer(options =>
    {
      options.AddEventHandler<ProcessErrorContext>(config => config.UseScopedHandler<RedirectOnErrorHandler>());
      options.AddEventHandler<ExtractAuthorizationRequestContext>(config => config.UseScopedHandler<SaveRequestHandler>());

      options.UseDataProtection();

      // Enable the authorization, logout, token and userinfo endpoints.
      options.SetAuthorizationEndpointUris("connect/authorize")
             .SetLogoutEndpointUris("connect/logout")
             .SetIntrospectionEndpointUris("connect/introspect")
             .SetTokenEndpointUris("connect/token")
             .SetUserinfoEndpointUris("connect/userinfo")
             .SetVerificationEndpointUris("connect/verify");

      options.RegisterScopes(Scopes.OpenId, Scopes.Email, Scopes.Phone, Scopes.Profile, Scopes.Roles, Scopes.OfflineAccess);

      options.AllowAuthorizationCodeFlow()
             .AllowPasswordFlow()
             .AllowRefreshTokenFlow();

      options.SetAccessTokenLifetime(TimeSpan.FromHours(1));
      options.SetRefreshTokenLifetime(TimeSpan.FromDays(30));

#if DEBUG
      options.AddDevelopmentEncryptionCertificate()
             .AddDevelopmentSigningCertificate();
#else
      // Register the signing and encryption credentials.
      // https://documentation.openiddict.com/configuration/encryption-and-signing-credentials.html#registering-a-certificate-recommended-for-production-ready-scenarios
      options.AddEncryptionCertificate(this.Configuration["OpenIddictEncryptionCertificateThumbprint"])
             .AddSigningCertificate(this.Configuration["OpenIddictSigningCertificateThumbprint"]);
#endif

#warning Remove if enough users have refreshed their token to the new OpenIddict 4.0 server tokens.
      options.DisableRollingRefreshTokens();

      options.UseAspNetCore()
             .EnableAuthorizationRequestCaching()
             .EnableLogoutRequestCaching()
             .EnableAuthorizationEndpointPassthrough()
             .EnableLogoutEndpointPassthrough()
             .EnableTokenEndpointPassthrough()
             .EnableUserinfoEndpointPassthrough()
             .EnableStatusCodePagesIntegration();
    })
    .AddValidation(options =>
    {
      options.UseDataProtection();
      options.UseLocalServer();
      options.UseAspNetCore();
    });
```

**Comment by kevinchalet** [comment]
Hey!

Thanks for sponsoring the project, much appreciated! 👍🏻 

> We are in the midst of migrating from OpenIddict 2.0 to v4.7. We've updated the old code with the new and a couple of things caught my eye.

Wooo, OpenIddict has had a few releases since the 2.0 milestone! Hope you'll enjoy using the latest version 😄 

> Will these changes result in users having their tokens invalidated and being forced to login again as a result of the changed signing key?

No. The key point here is that OpenIddict < 3.0 used ASP.NET Core Data Protection by default for all types of tokens except identity tokens, so the ephemeral signing key you mention was only used for identity tokens, which are typically short-lived and won't force your users to log in again as they are not used in the token refreshing process.

As long as you still have the same ASP.NET Core Data Protection master keys you had on your previous setup *AND* configure OpenIddict 3.0+ to use ASP.NET Core Data Protection (which is now opt-in) as you did, you shouldn't see any interruption of service.

> I'm disabling rolling refresh tokens because the refresh tokens that the users have can be many months old. I would except these refresh token would error out without adding `DisableRollingRefreshTokens()`. Is that assumption correct?

Nope, rolling refresh tokens - that are now enabled/opt-out by default as you figured out - don't prevent you from using old refresh tokens: what this feature does is preventing a client from using the same refresh token twice (by default, there's a 30-second leeway that allows replaying the token request to account for things like transient connection issues): if a client doesn't use the new refresh token returned in the refresh token response and tries to reuse an already redeemed refresh token, the entire chain of tokens and the corresponding authorization are revoked and the user must log in again to get a new refresh token.

This security measure is recommended by the OAuth 2.0 best practice RFC, but you can change the default leeway using `options.SetRefreshTokenReuseLeeway()` or disable it completely if necessary (e.g if you have non-standard clients that reuse tokens or clients running on road-warrior machines that are impacted by persistent network issues).

Hope it'll help 😃

**Comment by GuidoNeele** [comment]
Hey Kevin,

Thank you for your work on OpenIddict in general and answering my question with such detail! Very much appreciated.

> Nope, rolling refresh tokens - that are now enabled/opt-out by default as you figured out - don't prevent you from using old refresh tokens: what this feature does is preventing a client from using the same refresh token twice (by default, there's a 30-second leeway that allows replaying the token request to account for things like transient connection issues): if a client doesn't use the new refresh token returned in the refresh token response and tries to reuse an already redeemed refresh token, the entire chain of tokens and the corresponding authorization are revoked and the user must log in again to get a new refresh token.
> 
> This security measure is recommended by the OAuth 2.0 best practice RFC, but you can change the default leeway using options.SetRefreshTokenReuseLeeway() or disable it completely if necessary (e.g if you have non-standard clients that reuse tokens or clients running on road-warrior machines that are impacted by persistent network issues).

Just to clarify. I'm assuming the refresh tokens that our clients are using currently all have their expiry date exceeded because we were not using rolling refresh tokens. (I'm also assuming the expiry date is stored in the token and not on the server.) Do I set `options.SetRefreshTokenReuseLeeway()` with a very long timespan, let's say `TimeSpan.FromDays(365)` to prevent them from being invalid or what other method can I use to disable this completely? This would be a temporary solution until I'm sure enough many clients have received a new refresh token.

Thanks again and have a nice weekend!

**Comment by kevinchalet** [comment]
Hey,

> Just to clarify. I'm assuming the refresh tokens that our clients are using currently all have their expiry date exceeded because we were not using rolling refresh tokens. (I'm also assuming the expiry date is stored in the token and not on the server.) Do I set `options.SetRefreshTokenReuseLeeway()` with a very long timespan, let's say `TimeSpan.FromDays(365)` to prevent them from being invalid or what other method can I use to disable this completely? This would be a temporary solution until I'm sure enough many clients have received a new refresh token.

Unless you explicitly set `OpenIddictServerOptions.RefreshTokenLifetime` to `null`, refresh tokens always have a maximum lifespan (14 days by default): once the date is reached, OpenIddict automatically rejects the refresh token and tells the caller the token is no longer valid.

In OpenIddict 1.0/2.0, no new refresh token was issued when performing a `grant_type=refresh_token` request but the expiration date of the existing refresh token was actually dynamically extended by overriding the expiration date attached to the refresh token entry in the database: that's why you think your existing refresh tokens are expired even if they are likely not (their expiration date was updated each time they were used in a `grant_type=refresh_token` request)

In OpenIddict 3.0, this (complex) mechanism was removed: instead, you now always get a new refresh token (with a unique identity and DB entry) with a fixed expiration date each time to send a `grant_type=refresh_token` request.

Refresh tokens issued by OpenIddict 2.0 should still be fully usable in a `grant_type=refresh_token` request received by OpenIddict 4.x without having to disable rolling tokens: in this case, a new refresh token will be automatically returned in the token response and the old refresh token (issued by OpenIddict 2.0) will be marked as redeemed in the DB (any attempt to reuse the old refresh token will result in a revocation of the entire chain after the reuse leeway period, so the client MUST use the new refresh token returned in the response).

> This would be a temporary solution until I'm sure enough many clients have received a new refresh token.

You shouldn't need to use `options.SetRefreshTokenReuseLeeway()` at all for your scenario 😃 

> Thanks again and have a nice weekend!

Have a great weekend too and thanks again for sponsoring the project! 👍🏻

**Comment by GuidoNeele** [comment]
Thanks Kevin! Your answer made me look deeper and with verbose logging I found the problem was with unprotecting the token instead of the OpenIddict configuration. I've been pulling my hairs until I found an issue with data protection and newer .NET versions https://github.com/dotnet/aspnetcore/issues/43682
https://learn.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?tabs=aspnetcore2x&view=aspnetcore-7.0#setapplicationname for more information.

After adding
```csharp
var contentRootPath = this.Environment.ContentRootPath.TrimEnd(Path.DirectorySeparatorChar);

services.AddDataProtection()
        .SetApplicationName(contentRootPath)
        ...
```
the issue was fixed and I got a new access token.

**Comment by kevinchalet** [comment]
Ah yeah, it's a well-known issue 😭 

(I had not realized you were also updating .NET, otherwise I'd have likely mentioned it as a potential source of pain, sorry)

> the issue was fixed and I got a new access token.

Glad to hear that! 👍🏻

**Comment by kevinchalet** [comment]
Doing some housecleaning, but feel free to reopen if you need additional details 😃
