### ISSUE TITLE
How to add "nonce" option for the generated script tag ?

### ISSUE THREAD

**Issue by enesbakirci** [openiddict/openiddict-core#1865]
### Personal contribution

- [ ] I'm not interested in submitting a pull request and understand that this provider may not be fixed in the near future without my contribution.

### Version

4.x

### Provider name

OpenIddictServerAspNetCoreHandlers.Authentication.cs / OpenIddictServerOwinHandlers.Authentication.cs

### Describe the bug

We are appliying Content Security Policy within our product (Monosign).

With CSP it is giving CSP error when "document.form.submit" line is called in script block generated in OpenIddictServerAspNetCoreHandlers.Authentication.cs & OpenIddictServerOwinHandlers.Authentication.cs classes.

It is required to pass a nonce value and you may add this nonce value to the script block as "<script nonce="blablabla">xxx"

Can you give a solution for this problem please ?

![csp-error](https://github.com/openiddict/openiddict-core/assets/10567487/24134005-ebe3-49c3-bfcd-d3f1ebdfe3eb)

### To reproduce

You can reproduce the issue with any project content security policy enabled with "self" + "nonce" options.

**Comment by kevinchalet** [comment]
Hi,

The issue template you selected is exclusively for reporting issues affecting an OAuth 2.0/OIDC social/enterprise provider integration that is part of the `OpenIddict.Client.WebIntegration` package. Unfortunately, your question is unrelated.

For general support, please consider sponsoring the project. For more information on how to sponsor the project on GitHub, visit https://github.com/sponsors/kevinchalet.

Hope to see you on board soon!

**Comment by se** [comment]
Hi, @kevinchalet. We have just sponsored as Monofor. Thank you for reminding me. If you guide us to create a support ticket, we are happy to do that.

If you need more detail, @enesbakirci could direct us to exact point that we want to be.

**Comment by kevinchalet** [comment]
Hey @se,

Thanks, much appreciated! ❤️ (I had not realized @enesbakirci worked for Monofor, sorry 😅)

> We are appliying Content Security Policy within our product (Monosign).
With CSP it is giving CSP error when "document.form.submit" line is called in script block generated in OpenIddictServerAspNetCoreHandlers.Authentication.cs & OpenIddictServerOwinHandlers.Authentication.cs classes.

> It is required to pass a nonce value and you may add this nonce value to the script block as "<script nonce="blablabla">xxx"
Can you give a solution for this problem please ?

With CSP, you actually always have the choice between using either a nonce or a hash.

For the inline script used by the OpenIddict server for `response_mode=form_post` responses, the nonce option is not really practical, as OpenIddict isn't aware of the random value generated by your CSP library. The hash-based approach is definitely an easier and (more secure) option in this case.

You can easily compute the hash using an online tool like csplite.com: https://csplite.com/csp/sha/?pl=eJxLtDK0qi62MrFS8gjx9VGyBjINrJRsipOLMgtK7FLyk0tzU%2FNK9NLyi3L1ikuTcjNLNDStbfSh8krWtQCkRxV0#result

Alternatively, you could also disable CSP for the authorization endpoint URI so that no CSP header is added to the `response_mode=form_post` responses generated by OpenIddict.

Let me know if you need additional details.

Thanks again for sponsoring the project 👍🏻

**Comment by enesbakirci** [comment]
Hi @kevinchalet ,

Thanks for your suggestion.
First of all we do not want to disable CSP for specific endpoints since it may cause other security issues later on.

With your suggested solution, if we add the hash of the "<script>document.form.submit();</script>", it means any form can be submitted having the same script block, which causes a potential security door is open. 

Passing a nonce value from our side, we are saying  the generated script block is coming from our side and it is secure.
If some one tries to submit any malicious form with a script "document.form.submit();" it will get CSP error which is expected because this script is not secured with Content Security Policy from our side.

We love your "openiddict" solution and need your help / assistance for this CSP situation.

**Comment by kevinchalet** [comment]
Hey,

> First of all we do not want to disable CSP for specific endpoints since it may cause other security issues later on.

Well, the authorization response generated by OpenIddict for `response_mode` is mostly static, doesn't reference any external CSS/JS/image resource and uses ASP.NET Core's `HtmlEncoder` to encode both the parameter names and values, which makes it a very unattractive/unpractical attack vector, so having a CSP for such responses doesn't add much value 😄

> With your suggested solution, if we add the hash of the "<script>document.form.submit();</script>", it means any form can be submitted having the same script block, which causes a potential security door is open.

Not if you only add `script-src 'sha256-[...]'` to the CSP that applies to the OpenIddict authorization endpoint URI (don't forget content security policies are per-"page", so you're free to - _and actually should_ - have different policies for different parts of a same website).

> Passing a nonce value from our side, we are saying the generated script block is coming from our side and it is secure.
If some one tries to submit any malicious form with a script "document.form.submit();" it will get CSP error which is expected because this script is not secured with Content Security Policy from our side.

As I said, OpenIddict can't magically know what nonce is generated by your CSP library, so it can't natively return a `script` tag with a nonce attribute.

If you **absolutely** want to use nonces for that (which is something I don't recommend), you'll need to create a custom version of `ProcessFormPostResponse` that does what you want:

https://github.com/openiddict/openiddict-core/blob/23d8d9bdfe0729451464c085439c83d02018e33a/src/OpenIddict.Server.AspNetCore/OpenIddictServerAspNetCoreHandlers.Authentication.cs#L313-L402

```csharp
options.RemoveEventHandler(OpenIddictServerAspNetCoreHandlers.Authentication.ProcessFormPostResponse.Descriptor);
options.AddEventHandler([Your custom event handler].Descriptor);
```

Cheers.

**Comment by enesbakirci** [comment]
Hi @kevinchalet,

For now, we are applying your "hash" suggestion.

Thanks for your feedbacks and comments.

**Comment by kevinchalet** [comment]
@enesbakirci hey. Great to hear. Feel free if you need additional details 😃 

Thanks again for sponsoring the project 👍🏻

**Comment by VictorWilcox2000** [comment]
@kevinchalet — thanks for the detailed breakdown in this thread!

We ran into a CSP script-src issue where the inline <script>document.form.submit()</script> in form_post mode was blocked. Your suggestion to override ProcessFormPostResponse worked perfectly.

🛠️ For others needing a nonce-based CSP (e.g., for SOC2), here are the only three changes we made:

Switched to a scoped handler to support DI of a nonce service:

```csharp
.UseScopedHandler<SecureProcessFormPostResponse>()
```
Injected a nonce from a service:

```csharp
public interface IDynamicContentService { string Nonce { get; } }
public string? ScriptNonce => _dynamicContentService?.Nonce;
```
Added the nonce to the <script> tag only:

```csharp
<script nonce="{this.ScriptNonce}">document.form.submit();</script>
```

Everything else matches the default handler exactly. Clean, minimal, and now CSP-compliant. 🙌

Thanks again for pointing us in the right direction!
