### ISSUE TITLE
Why Just sponsors and contributors-only This Will Destory Openiddict Denude.IdentityServer Is Better

### ISSUE THREAD

**Issue by wisamidris7** [openiddict/openiddict-core#1881]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

4.x

### Describe the bug

yes

### To reproduce

ok

**Comment by SebastianStehle** [comment]
You would rather pay 1.500 EUR per year than like 60 (12 * 5) EUR per year? As an Open Source developer I understand the motivation to restrict support to contributors. It is a lot of unpaid work to maintain a library like this and especially corporations are not contributing as much as they should.

**Comment by kevinchalet** [comment]
OpenIddict is open source (Apache 2.0) and free to use, but support requests are sponsors/contributors-only because answering them is time consuming. Restricting them to sponsors is also a way to encourage individuals and companies to fund the project and ensure it is still actively developed.

If you're happy with IdentityServer, keep using it, it's a great project. OpenIddict does things differently and I like the fact folks have multiple choices and can opt for the stack they prefer. As of writing, OpenIddict has more than 70M downloads on NuGet.org, so it's safe to say it's used by lots of apps and not "in danger" 🤣 

Anyway, it's not the first time you're violating the rules of this project, which sadly forces me to block you from this repository. Hope you'll understand.

**Comment by kevinchalet** [comment]
@SebastianStehle

> As an Open Source developer I understand the motivation to restrict support to contributors. It is a lot of unpaid work to maintain a library like this and especially corporations are not contributing as much as they should.

❤️ 

> You would rather pay 1.500 EUR per year than like 60 (12 * 5) EUR per year?

It's also worth mentioning that there's a $2/month tier (less than a coffee a month) that allows individuals to submit support requests.

And for those who can't afford it or don't want to pay anything, you can still contribute to the project (e.g by writing blog posts, documentation or by submitting a web provider integration, which isn't hard at all and is a fairly well documented process: https://documentation.openiddict.com/guides/contributing-a-new-web-provider.html) and get free support 😃
