### ISSUE TITLE
Returning token directly

### ISSUE THREAD

**Issue by ghost** [openiddict/openiddict-core#195]
From the examples I'm seeing online it seems that the default way of authenticating someone directly is by setting a cookie via the LoginManager. 

As I'm using bearer tokens, I want to be able to return their access token, refresh token, etc, when they finish the registration process, rather than forcing them to make another API call to achieve this.

Is this possible in any way with OpenIddict?

**Comment by kevinchalet** [comment]
OpenIddict doesn't allow you to return a token outside an OpenID Connect request, deliberately.

To achieve what you want, you'll have to redirect your users back to the authorization endpoint, since it's the only place where you're allowed to ask OpenIddict to return an authorization code/access token/identity token as part of an authorization response.
