### ISSUE TITLE
Using the Velusia.Client sample the id_token and access_token are null and the @User.Identity.Name is null as well in the index.cshtml

### ISSUE THREAD

**Issue by kdudley21** [openiddict/openiddict-core#1962]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

5.1.0

### Question

I am using the Velusia example to play around with setting up a test client and authorization server. 
With the Velusia.Client it is coming back as authorized and there are some claims there but in the index.cshtml

@User.Identity.Name is null
and so is 

@await Context.GetTokenAsync("access_token")
and 
@await Context.GetTokenAsync("id_token")

Any idea why there are a handful of claims but these values are null ?

**Comment by kevinchalet** [comment]
Hey,

> @User.Identity.Name is null
and so is

That's because the OpenIddict client maps `ClaimTypes.Name` (the WS-Federation claim used by default by `ClaimsIdentity`'s constructor to populate the `IIdentity.Name` property) from the OpenID Connect `preferred_username` claim. Yet, this claim is not currently added by the server samples. I opened https://github.com/openiddict/openiddict-samples/pull/286 to improve that.

Since it's not a claim that is always added by identity providers, I also opened https://github.com/openiddict/openiddict-core/pull/1963 to update the client stack to fall back to the OIDC `name` claim when `preferred_username` is not present.

> @await Context.GetTokenAsync("access_token")
and
@await Context.GetTokenAsync("id_token")

It's expected, OpenIddict doesn't use these constants.

To retrieve the access token, use either:
  - `backchannel_access_token` (represented by the `OpenIddictClientAspNetCoreConstants.Tokens.BackchannelAccessToken` constant) for the access token returned by the token endpoint (only applies to flows where the token endpoint is used, e.g the code flow).
  - `frontchannel_access_token` (represented by the `OpenIddictClientAspNetCoreConstants.Tokens.FrontchannelAccessToken` constant) for the access token returned directly by the authorization endpoint (e.g implicit or hybrid flows where you specify `response_type=token`).

Same logic for the identity token.

Hope it'll help.

**Comment by kdudley21** [comment]
Thank you so much for your response ! That clears up the confusion I had

**Comment by kdudley21** [comment]
It looks like in Velusia the FrontchannelAccessToken and FrontchannelIdentityToken are null but the backchannel tokens are populated. Is that configured somewhere in the client to not send the FrontChannel tokens ?

Thanks again for all your help. I pulled down your changes this morning and the identity name is being populated perfectly now

**Comment by kevinchalet** [comment]
> Thank you so much for your response ! That clears up the confusion I had

Glad I could help 😄 

> It looks like in Velusia the FrontchannelAccessToken and FrontchannelIdentityToken are null but the backchannel tokens are populated. Is that configured somewhere in the client to not send the FrontChannel tokens ?

It's expected: this sample uses the authorization code flow, in which all the tokens are returned by the token endpoint. As I mentioned, the frontchannel tokens are only available when using the implicit or hybrid flows with `response_type=token` or `response_type=id_token`, which isn't something I recommend in most cases.

**Comment by kdudley21** [comment]
Ohhhh ok I gotcha !

From what I understand the backchannel and authorization code flow is more popular anyways so this is perfect.

Thanks !

**Comment by kevinchalet** [comment]
> From what I understand the backchannel and authorization code flow is more popular anyways so this is perfect.

Yep! When negotiating the `grant_type`/`response_type` combination (based on the client configuration and the server metadata), the OpenIddict client will always prefer the authorization code flow, as it's the best option available.

If you're interested in the gnarly details, you can find the (complex) logic here, with a few comments indicating why some flows are preferred to others: https://github.com/openiddict/openiddict-core/blob/b386b7844c643818b9664378ca20ff884b4f5c6a/src/OpenIddict.Client/OpenIddictClientHandlers.cs#L4354-L4544

**Comment by kevinchalet** [comment]
Closing as I believe I addressed all your concerns, but feel free to reopen if you have additional questions 😃
