### ISSUE TITLE
Claims not found in token of external provider (Microsoft)

### ISSUE THREAD

**Issue by AGIS-Development** [openiddict/openiddict-core#2049]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

5.01

### Question

Hi Kevin

We use external providers to authenticate users from there e-mail address. This works perfect.
Now we want to use the users Azure-AD groups to synchronise with our user groups. 
We added aditional claims to our Azure 'Identity Application' as described by Microsoft like this:
`	"optionalClaims": {
		"idToken": [
			{
				"name": "groups",
				"source": null,
				"essential": false,
				"additionalProperties": [
					"sam_account_name",
					"cloud_displayname"
				]
			}
		],
		"accessToken": [
			{
				"name": "groups",
				"source": null,
				"essential": false,
				"additionalProperties": [
					"sam_account_name",
					"cloud_displayname"
				]
			}
		],
		"saml2Token": [
			{
				"name": "groups",
				"source": null,
				"essential": false,
				"additionalProperties": [
					"sam_account_name",
					"cloud_displayname"
				]
			}
		]
	},`

We implemented a service derived from 'IClaimsTransformation' to access the token-claims when handled by OpenIdDict
but the additional claims never show up.

Do we miss something on the side of our OpenIdDict implementation?

Thanks for your help.

Kind regards
Christian

**Comment by kevinchalet** [comment]
Hey @AGIS-Development,

> Do we miss something on the side of our OpenIdDict implementation?

Yeah, it's likely. For a claim to appear in an access or identity token, two things must be done:
  - The claim must be present in he `ClaimsPrincipal` you use when calling `SignIn(principal, OpenIddictServerAspNetCoreDefaults.AuthenticationScheme)`.
  - The claim must include an `access_token` and/or `identity_token` claim destination to allow OpenIddict to copy it to the access token and/or identity token principals. See https://documentation.openiddict.com/configuration/claim-destinations.html for more information about this feature.

Hope it'll help 😃

**Comment by AGIS-Development** [comment]
Hi Kevin, thanks for you response.
When I evaluate the request from external login in `Authorize()` and `Exchange()` where it is received from OpenIdDict with this code
`var request = HttpContext.GetOpenIddictServerRequest() ??
			throw new InvalidOperationException("The OpenID Connect request cannot be retrieved.");`,
the request does not contains the Microsoft-claims 'groups' as expected.
Does this mean that these claims are not included in the Microsoft token or are they lost by 'GetOpenIddictServerRequest()'? 

Thanks again for your help.
Christian

**Comment by kevinchalet** [comment]
> When I evaluate the request from external login in `Authorize()` and `Exchange()` where it is received from OpenIdDict with this code
> `var request = HttpContext.GetOpenIddictServerRequest() ?? throw new InvalidOperationException("The OpenID Connect request cannot be retrieved.");`,
> the request does not contains the Microsoft-claims 'groups' as expected.

Claims are rarely (not to say never) present in the request details. Instead, they are extracted and validated from identity tokens or userinfo responses while doing the external authentication dance (which isn't something handled by the OpenIddict server).

Your authorization controller should be looking for these claims in the `ClaimsPrincipal` instance resolved from the authentication cookie. Here's an example using the default authentication scheme (you can specify a different scheme if necessary):

https://github.com/openiddict/openiddict-core/blob/6ac8c2c53ef4008376b1b408d17efef13354a3b3/sandbox/OpenIddict.Sandbox.AspNetCore.Server/Controllers/AuthorizationController.cs#L64-L73

If the claim is not present in the claims collection, it means it wasn't preserved while doing the external authentication dance. How to fix that depends on what component you're using:
  - When using the OpenIddict client (the recommended option), you must tweak your **authentication controller** to simply copy the claims you need to the cookie principal so that you can later retrieve them in your **authorization controller**. Here's an example:

https://github.com/openiddict/openiddict-core/blob/6ac8c2c53ef4008376b1b408d17efef13354a3b3/sandbox/OpenIddict.Sandbox.AspNetCore.Server/Controllers/AuthenticationController.cs#L53-L68

  - When using the MSFT OIDC handler, many claims are imported from the identity tokens but not from userinfo responses. For that, you may need a custom claim action. See https://leastprivilege.com/2017/11/15/missing-claims-in-the-asp-net-core-2-openid-connect-handler/ for more information.

Note: if you're using ASP.NET Core Identity and are treating Azure AD as an Identity external provider, implementing that will require doing more work as the external claims are not preserved by Identity. These two references should put you on the right track:
  - https://learn.microsoft.com/en-us/aspnet/core/security/authentication/social/additional-claims?view=aspnetcore-8.0
  - https://stackoverflow.com/a/42670559/542757

Probably not the simple answer you were expecting, but it's a complicated thing 😄

**Comment by AGIS-Development** [comment]
Hi Kevin

Yes, as you said, ' it's a complicated thing'. 
Because we couldn't get it to work and because of the time pressure, we decided to implement the role synchronization with GraphAPI.
Thanks for your help.

Christian

**Comment by kevinchalet** [comment]
>  Because we couldn't get it to work and because of the time pressure, we decided to implement the role synchronization with GraphAPI.

Ah yeah, that works too 👍🏻

Glad you found a working solution!
