### ISSUE TITLE
Using "role" claims from external providers in access tokens

### ISSUE THREAD

**Issue by karlschriek** [openiddict/openiddict-core#2053]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

5

### Question

We are currently setting up OpenIddict as identity provider for a system that has the following characteristics
- External login is possible from Azure AD (on a single Azure AD Application, controlled by us). Other external logins are planned, but are not relevant right now.
- A single client handles login. From there downstream calls are made to several resource servers (controlled by us)
- We want to control calls to resource server with Scopes (broadly) and Roles (specifically). The "api_1_scope" Scope for example would allow a user to get an access token with the "api_1_resource" audience. The "api_1_admin_role" Role would allow that user to call specific privileged endpoints on the api.
- Roles we want to be able to have originate from the "roles" claim of the external identity
- Scopes/Resources we want to want to handle by explicitly setting them in Server / Client / Api (how to do this is fairly clear to us based on the Zirku sample). However we would also like to be able to dynamically request scopes from the client, i.e. depending on the situation request an access token for api_1_resource, but not for api_2_resource.

We have two concrete questions on setting up the above:

# Question 1: Using "roles" from external providers.

Based on the "Velusia" sample, with the following section added:

```c#
options.UseWebProviders()
    .AddMicrosoft(options =>
        {
            options.SetClientId(Configuration["AzureAd:ClientId"]);
            options.SetClientSecret(Configuration["AzureAd:ClientCredentials:0:ClientSecret"]);
            options.SetTenant(Configuration["AzureAd:TenantId"]);
            options.SetRedirectUri("callback/login/microsoft");
        }
    );
```

The sample now exposes a "Microsoft Account/Entra ID" button. Logging in via this button results in a callback going to the "AuthenticationController". If we scrutinize `var result = await HttpContext.AuthenticateAsync(OpenIddictClientAspNetCoreDefaults.AuthenticationScheme);` here we see that `result.Principal.GetClaim("roles")` equals `"api_1_admin_role"`, which is a role that has been added to my Azure AD user on the Azure Ad Application linked in the `AddMicrosoft` section.

I would like to be able to attach `api_1_admin_role` as a `role` in claims for any access tokens that are created. There are three possible ways I can think of to make this happen. Perhaps you can comment on which of these are feasible and then give us some guidance on going about it?

1 Preferably, if possible,  we would like get the role directly from the external auth token and attach it to access tokens that are created for `api_1_resource` and `api_2_resource`
3.  If that is not possible, persist the role in the `AspNetRoles` and `AspNetUserRoles` table. Upon completing the registration some of the claims from the external identity are persisted in the OpenIddict database, but the role is not one of them and I am not sure how to go about setting that up. We would need to keep this in sync somehow (e.g. new roles added or old ones revoked), so would need to trigger updates somehow whenever a new identity token is fetched.
2. Persist the role, but do so via an external syncing process. Some kind of CRON job or the like that queries the MS graph, finds all users on the Azure AD Application as well as their roles, and then does CRUD directly on the `AspNetUser`, `AspNetUserLogins`, `AspNetRoles` and `AspNetUserRoles` tables. One difficulty with this approach is that in the `AspNetUserLogins` table the `ProviderKey` field is taken from the `sub` claim, which is some kind of encoded string that unique identifies user, tenant and application on Azure AD. How this string is defined is not documented by Microsoft and we have no way to accurate predict what it would be. We can make our own `{user_id}-{app_client_id}-{tenant_id}` string which would amount to the same thing, but there would need to be some way to override the functionality that uses the `ProviderKey` with this.

# Question 2: Dynamically specifying "scopes" in access token.

From the client we authenticate an identity (in the LogInCallBack) as follows:

`var result = await HttpContext.AuthenticateAsync(OpenIddictClientAspNetCoreDefaults.AuthenticationScheme);`

From this we can construct an `identity` object and then use that to call `SignIn(new ClaimsPrincipal(identity), properties)`. As far as I can tell, this is what requests that the access token be created.

We can then access this token with `var token = await HttpContext.GetTokenAsync(OpenIddictClientAspNetCoreConstants.Tokens.BackchannelAccessToken);`

Our question here is much more straightforward, and that is, how do we specify which claims should be included in this specific access token? I.e., even though the client is allowed to ask for `api_1_scope` and `api_2_scope`, in a specific call we might want to create an access token that is valid only for `api_1_scope`.

By default the access tokens seem to always include the scopes defined in:

```c#
.AddClient(options =>
    {
        
        ...
        options.AddRegistration(new OpenIddictClientRegistration
        {
            ClientId = "sample_client",
            ...
            Scopes = { Scopes.Email, Scopes.Profile, Scopes.OpenId, "api_1_scope", "api_2_scope"},
        });

    });
```

**Comment by kevinchalet** [comment]
Hey @karlschriek,

> From this we can construct an `identity` object and then use that to call `SignIn(new ClaimsPrincipal(identity), properties)`. As far as I can tell, this is what requests that the access token be created.

The flow is actually a bit more complicated/elaborate than that: unless you're doing something very special, the call to `SignIn(new ClaimsPrincipal(identity), properties)` - that uses the default challenge scheme configured in the ASP.NET Core authentication options (which is typically an instance of a cookie handler managed by ASP.NET Core Identity) - **will actually return an authentication cookie - and not a token -** and redirect the user to the return URL initially attached to the query string.

If that external authentication flow was triggered as part of an OIDC login dance for your own OpenIddict-based authorization server, that return URL will point to the /authorize endpoint. Assuming your implementation doesn't do anything fancy, that endpoint action will resolve the user claims from the authentication cookie created during the previous step and eventually call `SignIn(new ClaimsPrincipal(identity), OpenIddictServerAspNetCoreDefaults.AuthenticationScheme)` if the demand was accepted: it's what will trigger the generation of the tokens and a proper OIDC response.

> 1 Preferably, if possible, we would like get the role directly from the external auth token and attach it to access tokens that are created for `api_1_resource` and `api_2_resource`

It's definitely possible. For that, you'd need to do two things:
  - Store these claims in the authentication cookie (i.e the principal used in `AuthenticationController` when calling `SignIn(new ClaimsPrincipal(identity), properties)`): it's easy to do, but it's worth noting you may hit cookie size limits if you store too many/too large claims so try to be reasonable 😄

  - Copy these claims to the principal used for the `SignIn(new ClaimsPrincipal(identity), OpenIddictServerAspNetCoreDefaults.AuthenticationScheme)` call in `AuthorizationController` so that they are preserved in the authorization codes/refresh tokens and can be retrieved at any point in the chain. Depending on what you want to do (do you want the client to access these claims? The resource servers? Both?), you'll want to add `access_token` and/or `id_token` to the claim destinations attached to your `role` claims.

That said, it's worth noting that it may take time for these roles to propagate as it will require doing an Entra ID login dance and retrieving a refreshed Entra ID identity for new roles to be added in the authentication cookie and in OpenIddict tokens.

If you need something faster that doesn't require re-doing an Entra ID login dance, using the Graph client at the authorization server level (e.g in your `Exchange` action for the `refresh_token` grant, so that new tokens always get the correct roles) or at the resource server level - e.g using claims transformation: https://learn.microsoft.com/en-us/aspnet/core/security/authentication/claims?view=aspnetcore-8.0 - might be a good option.

> Our question here is much more straightforward, and that is, how do we specify which claims should be included in this specific access token? I.e., even though the client is allowed to ask for `api_1_scope` and `api_2_scope`, in a specific call we might want to create an access token that is valid only for `api_1_scope`.
> 
> By default the access tokens seem to always include the scopes defined in:

You can override the scopes attached to the client registration per-challenge by...
  - ... setting `InteractiveChallengeRequest.Scopes` for a console/GUI .NET app:

```csharp
var result = await _service.ChallengeInteractivelyAsync(new()
{
    CancellationToken = stoppingToken,
    ProviderName = provider,
    Scopes = ["api_1_scope"]
});
```

  - ... attaching a custom property to `AuthenticationProperties` for an ASP.NET Core app and adding an event handler that will retrieve it and attach it to the authorization request:

```csharp
var properties = new AuthenticationProperties(new Dictionary<string, string>
{
    // Note: when only one client is registered in the client options,
    // specifying the issuer URI or the provider name is not required.
    [OpenIddictClientAspNetCoreConstants.Properties.ProviderName] = provider
})
{
    // Only allow local return URLs to prevent open redirect attacks.
    RedirectUri = Url.IsLocalUrl(returnUrl) ? returnUrl : "/"
};

// Attach a custom property that will be used to override the requested scopes.
properties.SetString(".scope", "api_1_scope");

// Ask the OpenIddict client middleware to redirect the user agent to the identity provider.
return Challenge(properties, OpenIddictClientAspNetCoreDefaults.AuthenticationScheme);
```

```csharp
options.AddEventHandler<OpenIddictClientEvents.ProcessChallengeContext>(builder =>
{
    builder.UseInlineHandler(context =>
    {
        if (context.Properties.TryGetValue(".scope", out string scope))
        {
            context.Scopes.Clear();
            context.Scopes.UnionWith(scope.Split([" "], StringSplitOptions.RemoveEmptyEntries));
        }

        return default;
    });

    builder.SetOrder(OpenIddictClientHandlers.AttachScopes.Descriptor.Order - 1);
});
```
Note: in the next minor version, I'll add a built-in property in `OpenIddictClientAspNetCoreConstants.Properties` so adding a custom event handler will no longer be required in 5.5.0.

Hope it'll help 😃

**Comment by kevinchalet** [comment]
> Note: in the next minor version, I'll add a built-in property in `OpenIddictClientAspNetCoreConstants.Properties` so adding a custom event handler will no longer be required in 5.5.0.

I opened https://github.com/openiddict/openiddict-core/issues/2054 to track that.

**Comment by karlschriek** [comment]
In the Authentication callback I can add the "role" claim to the identity as follows:


```c#
        identity.SetClaim(ClaimTypes.Email, result.Principal.GetClaim(ClaimTypes.Email))
                .SetClaim(ClaimTypes.Name, result.Principal.GetClaim(ClaimTypes.Name))
                .SetClaim(ClaimTypes.NameIdentifier, result.Principal.GetClaim(ClaimTypes.NameIdentifier))
                .SetClaim(ClaimTypes.Role, result.Principal.GetClaim("roles")); <--- Added
```

It is being added as "http://schemas.microsoft.com/ws/2008/06/identity/claims/role"

![image](https://github.com/openiddict/openiddict-core/assets/25316920/a8e11ff2-33a1-41ff-810c-7cd12ea0025c)


However, I don't see how I can access this claim when the callback hits the Authorization callback.

This is the contents of result.Principal.Identity.Claims, the "http://schemas.microsoft.com/ws/2008/06/identity/claims/role" claim is not present.

![image](https://github.com/openiddict/openiddict-core/assets/25316920/bd42a657-9119-4c18-a8e6-b143190834b7)


What am I missing?

**Comment by kevinchalet** [comment]
> What am I missing?

That's because you're using ASP.NET Core Identity and treating Entra ID as an external ASP.NET Core Identity external provider. In this case, the flow is a bit more complicated: the default sign-in scheme - used when calling `SignIn(new ClaimsPrincipal(identity), properties)` - doesn't directly create the final authentication cookie (called "application cookie" in ASP.NET Core Identity) but creates an intermediate, temporary "external login cookie": sadly, the "external login cookie" -> "application cookie" mapping done by ASP.NET Core Identity is lossy: the claims you add in `AuthenticationController` are not preserved by Identity by default.

The two links at the end of this post should put you on the right track: https://github.com/openiddict/openiddict-core/issues/2049#issuecomment-2045767493

**Comment by kevinchalet** [comment]
> That's because you're using ASP.NET Core Identity and treating Entra ID as an external ASP.NET Core Identity external provider. In this case, the flow is a bit more complicated: the default sign-in scheme - used when calling `SignIn(new ClaimsPrincipal(identity), properties)` - doesn't directly create the final authentication cookie (called "application cookie" in ASP.NET Core Identity) but creates an intermediate, temporary "external login cookie": sadly, the "external login cookie" -> "application cookie" mapping done by ASP.NET Core Identity is lossy: the claims you add in `AuthenticationController` are not preserved by Identity by default.

I'll update the `AuthenticationController` present in the samples to mention that: while it's not specific to OpenIddict (since it also affects the Facebook/Google/Microsoft/Twitter OAuth 2.0 handlers maintained by the ASP.NET team), it's a common pitfall when using Identity and it's not easy to figure out what's going on when you're not familiar with the authentication stack or Identity.

**Comment by karlschriek** [comment]
Looking at https://learn.microsoft.com/en-us/aspnet/core/security/authentication/social/additional-claims?view=aspnetcore-8.0 it seems that we would need (among other things) to be able to set

```c#
    options.ClaimActions.MapJsonKey("urn:google:picture", "picture", "url");
    options.ClaimActions.MapJsonKey("urn:google:locale", "locale", "string");
```

But this functionality is not implemented in `options.UseWebProviders().AddMicrosoft( options => ...)` so where would we do this? I am not well enough versed with the frameworks in play here, but I am pretty sure this would mean cracking open a lot of abstractions...

The other link (https://stackoverflow.com/questions/42660568/asp-net-core-identity-extract-and-save-external-login-tokens-and-add-claims-to-l/42670559#42670559) looks to me like it is dealing with the part _before_ the loss of claims occurs. I think in this case it is dealing with appending a token, which will be persisted. But if you want to persist something else then this will also not be the solution in my opinion.

**Comment by kevinchalet** [comment]
> But this functionality is not implemented in `options.UseWebProviders().AddMicrosoft( options => ...)` so where would we do this? I am not well enough versed with the frameworks in play here, but I am pretty sure this would mean cracking open a lot of abstractions...

This part is not needed at all with the OpenIddict client as it doesn't do any claim filtering (like the OIDC handler developed by MSFT does): `HttpContext.AuthenticateAsync(OpenIddictClientAspNetCoreDefaults.AuthenticationScheme)` returns every possible claim OpenIddict was able to extract from the identity token or the userinfo response and it's up to you to add the claims you need to the cookie principal if you want to preserve them.

> The other link (https://stackoverflow.com/questions/42660568/asp-net-core-identity-extract-and-save-external-login-tokens-and-add-claims-to-l/42670559#42670559) looks to me like it is dealing with the part _before_ the loss of claims occurs. I think in this case it is dealing with appending a token, which will be persisted. But if you want to persist something else then this will also not be the solution in my opinion.

The sample shows how to persist the access token, but you can use the same exact approach to persist any claim: the "external principal" containing the claims you preserved in your `AuthenticationController` is exposed via `ExternalLoginInfo.Principal`: https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.identity.externallogininfo

If you don't want to scaffold the `ExternalLogin.cshtml` page, you can also override the default `SignInManager`: https://haacked.com/archive/2019/07/16/external-claims/

In any case, it's sadly something I can't improve on my side as it's completely outside OpenIddict's control (and trust me, I lobbied hard to to convince the ASP.NET team they should offer a better story for that...)
