### ISSUE TITLE
three-party login

### ISSUE THREAD

**Issue by wangyuzhu** [openiddict/openiddict-core#2188]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

5.8.0

### Question

Hello, I would like to ask if there is any way to quickly access three-party login. Existing ones are similar to existing google, github, etc. How can I code to implement three-party login such as baidu and alipay?Can this be achieved by implementing an interface?

**Comment by kevinchalet** [comment]
Hey,

It's indeed possible to add (and contribute!) new providers for the OpenIddict client, as explained in detail here: https://documentation.openiddict.com/guides/contributing-a-new-web-provider.

That said, Alipay is notoriously known for being a terrible OAuth 2.0 implementation (I'd even say it's the worst of the worst, and I've seen a lot in my career: https://github.com/openiddict/openiddict-core/issues/1451#issuecomment-1145034502 🤣). I wouldn't recommend trying to implement it yourself if you're not familiar with OpenIddict and its client stack.

Regarding Baidu, no idea (sadly, OAuth 2.0 services offered by Chinese companies are frankly almost always painful to support due to all the non-standard stuff they implement... 😭)
