### ISSUE TITLE
Redirect to original client from callback on external error

### ISSUE THREAD

**Issue by irq** [openiddict/openiddict-core#2220]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

5.2.0

### Question

We are using OpenIdDict and have a question regarding error handling. First I'll explain a bit about our setup and how we are using the library.
My organization queueit has sponsored.

We have an auth server which uses OpenIdDict to implement both the client and server aspects of OpenID Connect. This auth server enables authentication through various external providers. Currently, we only have one client using it for user authentication.

**User authentication Flow**
1. Authorization Request:
When an authorize request is received, we initiate external authentication by returning `Results.Challenge(properties, [provider]);`, which redirects the user to the chosen external provider. In the properties object, we include the client's original redirect_uri.

2. Callback Handling:
When the user returns from the external provider, our callback is triggered. We can then retrieve the original redirect_uri by accessing it in the properties on the authentication result:
`await context.AuthenticateAsync(OpenIddictClientAspNetCoreDefaults.AuthenticationScheme);`

3. Error Handling:
If an error occurs at any point in the process, we redirect the user back to the original client, where the error message is displayed.

**Issue**
The current setup works well except when an error is returned from the external provider. This could e.g. be if the user presses cancel instead of signing in. In this case, AuthenticateAsync fails, and the properties don't contain the redirect_uri. Note that I have enabled `EnableErrorPassthrough`.

**Question**
Is there a way to access the original request's redirect_uri even when authentication fails, so that we can return the user to the original client with an error message?

**Comment by kevinchalet** [comment]
Hey @irq,

> My organization queueit has sponsored.

Thanks a lot for sponsoring the project! ❤️ 

> Currently, we only have one client using it for user authentication.

In most cases, reusing a single client registration for multiple applications is strongly discouraged. If I understood correctly, your single client kinda acts like a gateway that redirects the user agent to other apps once the actual authentication is handled?

>  Is there a way to access the original request's redirect_uri even when authentication fails, so that we can return the user to the original client with an error message?

Unfortunately, it's not currently supported (as you figured out, only the error details are currently included in the "errored authentication properties" created by `OpenIddictClientAspNetCoreHandler`).

That said, it would certainly make sense to return more things in the errored authentication properties, including the target link URI (what ASP.NET Core calls `AuthenticationProperties.RedirectUri`). I'll work on that and include it in the next 6.0 preview.

Note: of course, not all errors will allow retrieving the target link URI: any error caused by a missing or invalid `state` token will cause that URI to be null, since OpenIddict has no way to resolve these properties when the `state` token cannot be extracted 😃 

Cheers.

**Comment by irq** [comment]
> In most cases, reusing a single client registration for multiple applications is strongly discouraged. If I understood correctly, your single client kinda acts like a gateway that redirects the user agent to other apps once the actual authentication is handled?

We are not re-using a client registration. I just meant that we have a single site which is a client of our auth server atm.

Thanks for the response. We will add a work-around for now and then implement the proper solution when available.

**Comment by kevinchalet** [comment]
> We are not re-using a client registration. I just meant that we have a single site which is a client of our auth server atm.

Ah, sorry. When you said "so that we can return the user to the original client with an error message?", I thought you said you wanted to redirect the user to another app :smiley:

> Thanks for the response. We will add a work-around for now and then implement the proper solution when available.

FYI, a new 6.0 preview including this change will ship this week and RTM will ship in December, before Christmas.

**Comment by irq** [comment]
Sounds good, will test with the preview. :)

**Comment by kevinchalet** [comment]
Preview4 just shipped: https://github.com/openiddict/openiddict-core/releases/tag/6.0.0-preview4 😃

**Comment by irq** [comment]
I've updated to the preview and everything works as expected. Thanks for the quick turnaround. Looking forward to the full release.

**Comment by kevinchalet** [comment]
Great! Thanks for giving it a try, @irq 👍🏻
