### ISSUE TITLE
Differents TKeys

### ISSUE THREAD

**Issue by felipesantanadev** [openiddict/openiddict-core#233]
There is some way to make the OpenIddictTokens be build with string key and the AspNetUsers to be build with int key?

When I use `ApplicationEntityDbContext : OpenIddictDbContext<ApplicationUserEntity, IdentityRole<int>, int>` the `OpenIddictTokens` table receive an int ID and It's not a good idea, since for each token request It will add a new row in the table with a new ID index and the INT data will overflow sometime.

**Comment by kevinchalet** [comment]
> There is some way to make the OpenIddictTokens be build with string key and the AspNetUsers to be build with int key?

Not with the default EF Core stores, nope. The `TKey` parameter impacts all the entities and there's no plan to introduce the ability to have separate key types for each entity (it would be a complete mess).

> When I use ApplicationEntityDbContext : OpenIddictDbContext<ApplicationUserEntity, IdentityRole<int>, int> the OpenIddictTokens table receive an int ID and It's not a good idea, since for each token request It will add a new row in the table with a new ID index and the INT data will overflow sometime.

Only authorization codes and refresh tokens are stored in this table. Since they are short-lived, their corresponding entry in the table will be quite ephemeral. Nothing prevents you from resetting the `auto_increment` counter. Alternatively, you can use `long`.

**Comment by felipesantanadev** [comment]
Ok, I understand what you mean. Do you think that leaving the default keys for all tables, a system which has a very large number of users will be lazy with the User ID not being INT or LONG?

And another question, just to understand the flow. When something is inserted in the Authorization table? Because only my OpenIddictTokens table has values, the OpenIddictAuthorizations table is empty.

**Comment by kevinchalet** [comment]
If using string primary keys had such a horrible perf' impact, I guess Identity wouldn't use them. That said, it's likely a question you should ask to the ASP.NET/EF team.

> When something is inserted in the Authorization table? 

Currently, never. This area is still a work in progress.
