### ISSUE TITLE
401 when trying to authenticate using token

### ISSUE THREAD

**Issue by asadsahi** [openiddict/openiddict-core#311]
Hi,

I am trying to follow this article for password flow with openiddict:

http://capesean.co.za/blog/asp-net-5-jwt-tokens/

Article seems a little outdated, but I have updated a clone of that repo with new changes. Here is my repo:

https://github.com/asadsahi/AspNetCoreJwtWithOpenId

I get the token but getting 401 when trying to call api. 

Can someone review my project to identify the cause of error and also if anything is missed in terms of password flow with openiddict?

Much appreciated.

Thanks

**Comment by kevinchalet** [comment]
Hey,

The issue was quite easy to spot: your app uses the JWT bearer middleware but doesn't ask OpenIddict to use JWT as the access token format:
  - https://github.com/asadsahi/AspNetCoreJwtWithOpenId/blob/master/Startup.cs#L96-L103
  - https://github.com/asadsahi/AspNetCoreJwtWithOpenId/blob/master/Startup.cs#L67

Note that Sean's article/sample is now obsolete (many things have changed between the alpha bits and the latest beta2 packages). I'd recommend reading https://blogs.msdn.microsoft.com/webdev/2016/10/27/bearer-token-authentication-in-asp-net-core/ instead.

You should also take a look at the password/refresh token flows samples:
  - https://github.com/openiddict/openiddict-samples/tree/master/samples/PasswordFlow
  - https://github.com/openiddict/openiddict-samples/tree/master/samples/RefreshFlow

If you don't need to support the other flows, you could simplify your code a lot.

**Comment by asadsahi** [comment]
@PinpointTownes Thanks for your response. I read that msdn article, but that wasn't end to end yet. 

Enabled that jwt option, but  still getting 401. Seems something else is missing too.

**Comment by kevinchalet** [comment]
You must also set the resources list when using JWT, as mentioned in the MSDN article ;)

**Comment by asadsahi** [comment]
Thanks @PinpointTownes is there a javascript based sample which I can quickly follow as I want to implement in Angular based SPA.

**Comment by asadsahi** [comment]
@PinpointTownes [RefreshFlow ](https://github.com/openiddict/openiddict-samples/tree/master/samples/RefreshFlow)sample seems close to what I want to achieve don't you think?

Would it hurt if I leave refresh token flow in application which only needs password flow with jwt e.g?

**Comment by kevinchalet** [comment]
> Would it hurt if I leave refresh token flow in application which only needs password flow with jwt e.g?

Heh no. You'll likely need to implement the refresh token flow if you need to refresh your access tokens, anyway :smile:

**Comment by asadsahi** [comment]
@PinpointTownes got two questions in order to resolve 401 issue I am having with the app which I mentioned earlier:
Question 1) If we add type as public for application as shown below:
![image](https://cloud.githubusercontent.com/assets/3470892/21597226/ecf34dac-d13e-11e6-8805-4741cd8fca3a.png)

In DB it adds it as confidential:
![image](https://cloud.githubusercontent.com/assets/3470892/21597230/fe904362-d13e-11e6-9442-8d566dc64899.png)

Is this correct?

Question 2) Getting 401 when trying to call test api controller secured with "testrole". Http request doesn't even hit controller action method even the token I get has that role in it:

![image](https://cloud.githubusercontent.com/assets/3470892/21597246/376b956a-d13f-11e6-91c4-94a04515b313.png)

Any idea why?

I have check all the resources added as per MSDN article and cannot identify which resource is missing. Can you please help with identifying the cause?

Here the my repo again:

https://github.com/asadsahi/AspNetCoreJwtWithOpenId

Thanks

**Comment by kevinchalet** [comment]
> Question 1) If we add type as public for application as shown below: In DB it adds it as confidential:

That's because you're using the overload taking a `secret` parameter: as mentioned in the XML documentation, OpenIddict considers the resulting application is necessarily confidential in this case and overrides the `Type` property.

I'll consider adding a check and throw an `InvalidOperationException` to help folks figure out they are doing something illogical.

> I have check all the resources added as per MSDN article and cannot identify which resource is missing. Can you please help with identifying the cause?

Here's the relevant part in the blog post:

> The ticket object allows us to use helpful OpenID Connect extension methods to specify scopes and resources to be granted access. In my sample, I pass the requested scopes filtered by those the server is able to provide. For resources, I provide a hard-coded string indicating the resource this token should be used to access. In more complex scenarios, the requested resources (request.GetResources()) might be considered when determining which resource claims to include in the ticket. Note that resources (which map to the audience element of a JWT) are not mandatory according to the JWT specification, though many JWT consumers expect them.

A bit more details about this feature can be found here: http://kevinchalet.com/2016/07/13/creating-your-own-openid-connect-server-with-asos-adding-custom-claims-and-granting-scopes/

**Comment by asadsahi** [comment]
Thanks @PinpointTownes , feeling so dumb right now. Didn't see the errors in console as it was clearly saying that audience resource was missing. So had to add resource server in ticket like:

```
   // Set the resource servers the access token should be issued for.
                // Multiple values can be specified, but they can't contain space characters.
                ticket.SetResources("resource_server", "http://localhost:5000/");
```

As you pointed out in your article, this is only required by Microsoft Jwt middleware but not standard requirement which means well defined :+1:
