### ISSUE TITLE
Format of error messages varies (not always json)

### ISSUE THREAD

**Issue by baserz** [openiddict/openiddict-core#331]
Hi!
I noticed that when for example using OpenIdConnectResponse to return messages (as the samples does) it returns in json format = ok. But certain built-in errors is returned as plain/text. For example, the client_id error seems to be returned as plain text. It would be good if all errors came in the same format (json) so as to avoid having to parse multiple formats. I dont know if this can be affected in some way, but setting Accept  header as application/json had no effect for example.

Calling authorize without client id:
```
HTTP/1.1 400 Bad Request
Date: Tue, 17 Jan 2017 05:49:40 GMT
Content-Length: 64
Content-Type: text/plain;charset=UTF-8
Server: Kestrel
Cache-Control: no-cache
Pragma: no-cache
Expires: -1

error:invalid_request
error_description:client_id was missing
```

Receiving an openidconnectresponse:

```
HTTP/1.1 400 Bad Request
Date: Tue, 17 Jan 2017 05:52:05 GMT
Content-Type: application/json; charset=utf-8
Server: Kestrel
Transfer-Encoding: chunked

54
{"error":"invalid_grant","error_description":"The username or password is invalid."}
0
```

**Comment by kevinchalet** [comment]
Hey,

That's actually the expected behavior: ASOS (the underlying OIDC framework behind OpenIddict) returns `application/json` for all the non-interactive endpoints (i.e "API endpoints" called by UI-less clients) and `text/plain` for the authorization and logout endpoints, as they are directly visible by the end users.

At some point, the `text/plain` response might be replaced by a nicer HTML error page.

**Comment by kevinchalet** [comment]
> At some point, the text/plain response might be replaced by a nicer HTML error page.

Note that you're encouraged to use the status code pages middleware when using OpenIddict, so you get a better error page. Take a look at the code flow sample to see how it works.

**Comment by baserz** [comment]
I was using the implicit flow, not the codeflow. But written on gitter instead, might be i misunderstood something then i regards to the intended flow.

**Comment by qvotaxon** [comment]
According to the RFC 6749 Standard error responses should always be returned in JSON format.
See section 5.2 for the error response definition:
https://www.rfc-editor.org/rfc/rfc6749#section-5.2

![image](https://user-images.githubusercontent.com/2746261/206681133-f739476e-6b82-41c9-82b0-3e9be27556ed.png)

Is there any way for me to force the API to return the exceptions in JSON format?

**Comment by qvotaxon** [comment]
> According to the RFC 6749 Standard error responses should always be returned in JSON format. See section 5.2 for the error response definition: https://www.rfc-editor.org/rfc/rfc6749#section-5.2
> 
> ![image](https://user-images.githubusercontent.com/2746261/206681133-f739476e-6b82-41c9-82b0-3e9be27556ed.png)
> 
> Is there any way for me to force the API to return the exceptions in JSON format?

Could you please explain to me how this is off-topic? 

The original question by ryhled was about responses from the OIDC server not always being returned in a JSON format. The RFC I linked to is the RFC for OAuth 2.0. I believe OpenIDConnect should adhere to this standard, since it's an OAuth 2.0 implementation. 

This standard states that error responses should be returned in json format. I understand your explanation as to why OpenIdDict doesn't return the responses in the expected format. However, my question is: Is there any way for me to force OpenIdDict to return responses in JSON format?

Thanks in advance!

**Comment by kevinchalet** [comment]
@qvotaxon as mentioned in https://github.com/openiddict/openiddict-core/issues/new/choose, questions and support demands are restricted to sponsors and contributors so trying to revive an almost 6-year-old topic is not exactly the best way to get your question answered.
