### ISSUE TITLE
Allowing simple configuraiton of auto-redirect back to the client app after an authentication error such as timeout

### ISSUE THREAD

**Issue by joshcomley** [openiddict/openiddict-core#377]
Currently if `EnableRequestCaching()` is being used and the session times out but the user still tries to log in, the following error message appears to the user:

`error:invalid_request`
`error_description:Invalid request: timeout expired.`

I can override this with a custom error controller, detect this error and ultimately redirect back to the client app to restart the login process, but this seems like a natural flow for most apps (user's don't care that something has timed out), so it would be good to have this as an option in the configuration without having to provide a custom controller that checks error strings:

`.RedirectToClientOnError = true` or some such like.

**Comment by IlyaShkapo** [comment]
Hello @PinpointTownes,

I faced with the same issue. When can we expect for this enhancement? 
What workaround can we implement to avoid this issue now?

Thanks.

**Comment by kevinchalet** [comment]
Yo,

The problem is that when the request_id is invalid (e.g because the cache entry was removed), all the request details like the client identifier or the redirect URL are lost. If we wanted to support what you suggest, we'd have to preserve the client_id/redirect_uri/state parameters and flow them alongside the request_id parameter, which would almost defeat the whole purpose of using it.

Instead, have you considered adding an HTML/JS link to allow the user to go back to the previous page (i.e the client app)?

```html
<a href="javascript:history.back()">Go back to the previous page</a>
```
