### ISSUE TITLE
How to reach signup page of openiddict authorization server?

### ISSUE THREAD

**Issue by zafrulhassan** [openiddict/openiddict-core#392]
I have built opeiddict as separate web application as authorization server. I am stuck with small problem, that is how I can go to user registration page directly though a link from the client web application. Right now I can go to login page, as your sample example:

 ```
public ActionResult SignIn() {
            // Instruct the OIDC client middleware to redirect the user agent to the identity provider.
            // Note: the authenticationType parameter must match the value configured in Startup.cs
            return new ChallengeResult(OpenIdConnectDefaults.AuthenticationScheme, new AuthenticationProperties {
                RedirectUri = "/"
            });
        }
```
Is there a way to go to authentication server Account/Register from client app?

**Comment by kevinchalet** [comment]
OpenIddict itself has no signup page (it's not an OpenID Connect concept), so it depends on how your authorization endpoint is implemented (in the sample, the user is redirected to the main login page, that also allows them to register).

You could use a specific OIDC request parameter to tell your authorization endpoint - the `Authorize` action in the sample - that you'd like the user to be redirected to the registration page instead of the login page. Since this is mainly a client-side question, consider asking your question here: https://github.com/aspnet/Security
