### ISSUE TITLE
Relax the refresh token policy to exclude client_id & client_secret

### ISSUE THREAD

**Issue by capesean** [openiddict/openiddict-core#40]
A public client needs to send the client_id and client_secret in order to refresh a token. It would be much better to relax this constraint and let the refresh token be used without needing to send this information, or using workarounds like hidden frames and cookies, etc.

**Comment by kevinchalet** [comment]
Here's the relevant check (in `OpenIddictProvider.ValidateTokenRequest`):

``` csharp
// Note: in pure OAuth2, client authentication is not required for non-confidential client applications like mobile apps
// but OpenIddict uses a stricter policy that makes client authentication mandatory when using the refresh token grant type,
// as required by the OpenID Connect specification: http://openid.net/specs/openid-connect-core-1_0.html#RefreshingAccessToken
// When client_id and/or client_secret is/are missing, an error is returned to the client application.
if (context.Request.IsRefreshTokenGrantType() && (string.IsNullOrEmpty(context.ClientId) ||
                                                  string.IsNullOrEmpty(context.ClientSecret))) {
    context.Reject(
        error: OpenIdConnectConstants.Errors.InvalidRequest,
        description: "Client authentication is required when using the refresh token grant.");

    return;
}
```

As mentioned in the associated comment, client authentication is **required** by the OpenID Connect core specification so we shouldn't - _in theory_ - allow public applications to use the refresh token grant.

That said, I agree this is not ideal from a usability perspective (specially when using the resource owner password grant, where making a `prompt=none` authorization request is not an option). Although it has specific security implications, I'm tempted to think it's still better to support it than forcing users to use worse alternatives (like storing user credentials to make a new ROPC request instead of a refresh token request).

So :+1:

**Comment by chrisjmccrum** [comment]
I second that, from a usability perspective, requiring the client authentication should be optional.  We're in the midst of developing a front end angular app and are jumping through unnecessary hoops to use refresh tokens. Inevitably with the help of the community we are circumventing this obstacle but it all seems like a round-a-bout solution to a simple adjustment to the OpenID Connect specification.
