### ISSUE TITLE
Wrong table names with netcoreapp2.0 /EF Core 2 when using OpenIddict

### ISSUE THREAD

**Issue by ghost** [openiddict/openiddict-core#428]
Hi there,

I just upgraded my existing netcore1.1 app to 2.0 (including new Openiddict version) and got it working basically. 
But as soon as I tried to query my existing database via EF Core 2.0 I saw that my sql queries do not use my DbSet table names (e.g. "Pharmacies") but instead use the Entity name "Pharmacy". 
The moment I comment out ._UseOpenIddict();_ within my _"services.AddDbContext"_ section, everything works as it should and my query is against "Pharmacies".  

So it seems OpenIddict kind of overwrites the standard behaviour?

Any hint where I can fix that? Thanks ;)

**Comment by kevinchalet** [comment]
Hi @MoxxNull,

This bug was reported on Gitter by @bradmarder a few weeks ago: https://gitter.im/openiddict/openiddict-core?at=59710e43f5b3458e306809a1.

We haven't dug enough to determine what's causing it, but my feeling is that it's a regression in EF Core 2.0 because the code that registers the OpenIddict models in the model builder hasn't changed between OpenIddict 1.0 and 2.0 (and yet it works fine with OpenIddict 1.0 + EF Core 1.0).

That would be great if you could isolate the bug and provide the EF team a repro that doesn't include OpenIddict.

**Comment by ghost** [comment]
Ah thanks for the link, I didn't check gitter.  Okay, I'll see what I can do!

**Comment by kevinchalet** [comment]
FYI, here's the EF thread: https://github.com/aspnet/EntityFramework/issues/9225 (it was closed because no repro was provided to the EF team)

**Comment by ghost** [comment]
I've uploaded a project to reproduce the error. Therefor I modified your code to a minimum to produce the error : https://github.com/MoxxNull/efcore2test

To be honest I have no idea about the whole Customizer stuff and just copied that :)

Hope that helps  (posted it in EF Core thread aswell)

**Comment by kevinchalet** [comment]
Awesome @MoxxNull, thanks for taking the time to do that :clap:

**Comment by gizmohd** [comment]
OK guys.. I had this Exact same issue.. and was hitting my head against the wall...   Eventually I found a work around.. which almost seems to go against the current logic... 

I noticed that with all of the Openiddict services disabled.. My EF tables and data were returning as expected.  But.. When i enabled the  options.UseOpenIddict(); in this section.. Things broke again..

      // Add framework services.
            services.AddDbContext<ApplicationDbContext>(options =>
                {
                    options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection"));
                    // Register the entity sets needed by OpenIddict.
                    // Note: use the generic overload if you need
                    // to replace the default OpenIddict entities.
                    //options.UseOpenIddict();
                });

I renabled everything in the startup.cs config as mentioned in previous instructions, and made some tests.. Granted, I only needed the password flow.. since I am integrating a mobile application into my site.  But bu leaving the options.UseOpenIddict(); DISABLED, everything works...  I checked my database, and tokens are storing as I expected...  Initially I was having a problem getting my bearer tokens to authorize, until I stumbled upon the change to the Authorize attribute...   Once I replaced [Authorize] with [Authorize(AuthenticationSchemes = AspNet.Security.OAuth.Validation.OAuthValidationDefaults.AuthenticationScheme)], my bearer token calls began to work.

so.. At least for me, I'm good.. OpenIddict Aspnet core 2.0 is working as I had hoped... and I'm able to continue on the migration and development of my sites... 

My question here is this:   Did 'breaking changes' in the 2.0 framework negate the necessity of specifically calling the Options.UseOpenIddict()...

Note:  as I was typing the above line... I realized that I was still referencing the builder.UseOpenIddict() line in the ApplicationDbContext file... I have just removed that line and re-enabled the options.useopeniddict() line and my EF tables are broken again... SO.. it appears the issue lies with initializing the UseOpenIddict() in the options... When intialized in the ApplictionDbContext file under OnModelCreating it works.. and I have no EF troubles....

        protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder);
            // Customize the ASP.NET Identity model and override the defaults if needed.
            // For example, you can rename the ASP.NET Identity table names and more.
            // Add your customizations after calling base.OnModelCreating(builder);

           builder.UseOpenIddict();
        }
So, hopefully that will give you a better insight as to how to troubleshoot and hopefully fix... Maybe it;s just as simple as ONLY initializing in the ApplicationDbContext file...

**Comment by kevinchalet** [comment]
> So, hopefully that will give you a better insight as to how to troubleshoot and hopefully fix...

Thanks for the detailed feedback :+1: 

> Maybe it;s just as simple as ONLY initializing in the ApplicationDbContext file...

Using the `ModelBuilder` extension is indeed one potential workaround: it achieves the same result, but unlike the `DbContextOptionsBuilder` extension, it doesn't have to register an `IModelCustomizer` to be able to register the OpenIddict entities.

The very cool thing with the `DbContextOptionsBuilder` extension is that it allows you to register the OpenIddict entities in Startup.cs instead of in your DB context. It's particularly useful if your context is part of a DAL project and if you don't want to reference the OpenIddict packages there.

Note: we're likely going to use the workaround suggested by the EF team to ensure our model customizer doesn't mess up with the default relational customizer (that is responsible of determining the right table name from the `DbSet` property): https://github.com/openiddict/openiddict-core/pull/431.

**Comment by ghost** [comment]
2.0.0-preview1-0648 seems to work as it shoud, thanks for fixing!
