### ISSUE TITLE
Decryption ClientSecret from OpenIddictApplications table

### ISSUE THREAD

**Issue by maksym-devpro** [openiddict/openiddict-core#452]
Hello everyone

Please help me with decryption ClientSecret from OpenIddictApplications table.

How can I decrypt ClientSecret ?

kind regards

**Comment by kevinchalet** [comment]
Hey,

Client secrets are not encrypted, they are irreversibly hashed: https://github.com/openiddict/openiddict-core/issues/418#issuecomment-315090786.

Can you tell me more about your scenario?

**Comment by maksym-devpro** [comment]
User want to see unencrypted ClientId on admin page for transfer their third-party services to access our service

I did not find a function that allows you to get the original ClientSecret from database

If I understand right your previous message  this code does not help me get the original ClientSecret

  IServiceScope scope = servicesProvider
                .GetRequiredService<IServiceScopeFactory>()
                .CreateScope();

            var store =  scope.ServiceProvider.GetRequiredService<OpenIddictApplicationStore<ApplicationDbContext>>();


CancellationToken cancellationToken = new CancellationToken();
string сlientId = await store.GetClientIdAsync(application, cancellationToken);

Am I right ?

**Comment by kevinchalet** [comment]
> I did not find a function that allows you to get the original ClientSecret from database

There's no such thing because the secret is hashed: the original value can't be retrieved.

If you absolutely need to support this scenario, consider subclassing `OpenIddictApplicationManager` and overriding `ObfuscateClientSecretAsync()`/`ValidateClientSecretAsync()` to use your own encryption/hashing strategy.

https://github.com/openiddict/openiddict-core/blob/ae54086ae993d17cf884cf0a719fa3f1bd0c65a8/src/OpenIddict.Core/Managers/OpenIddictApplicationManager.cs#L708

https://github.com/openiddict/openiddict-core/blob/ae54086ae993d17cf884cf0a719fa3f1bd0c65a8/src/OpenIddict.Core/Managers/OpenIddictApplicationManager.cs#L729
