### ISSUE TITLE
SignalR + Token

### ISSUE THREAD

**Issue by antonsacz** [openiddict/openiddict-core#467]
Hi,

I'm trying to map signalR sessionId with user account. To identify the user I'm sending to Hub token and trying to resolve it into user identity. Is it possible to do it this way? May be there are some other options to identify user with signalR?

Thanks,
Anton

**Comment by kevinchalet** [comment]
Hey,

You can send the access token in the `Authorization` header as part of the handshake request like you'd do with any other API.

Unfortunately, this won't work well with browser-based clients because the WebSockets JS API doesn't offer a way to set the request headers. In this case, the recommended approach is to use a query string parameter. Here's how you can force the OpenIddict validation handler to use it:

```csharp
services.AddOpenIddict()
    .AddValidation(options =>
    {
        options.AddEventHandler<OpenIddictValidationEvents.RetrieveToken>(
            notification =>
            {
                notification.Context.Token = notification.Context.Request.Query["access_token"];

                return Task.CompletedTask;
            });
    });
```

... or if you're still using the aspnet-contrib validation handler:

```csharp
services.AddAuthentication()
    .AddOAuthValidation(options =>
    {
        options.Events.OnRetrieveToken = context =>
        {
            context.Token = context.Request.Query["access_token"];

            return Task.CompletedTask;
        };
    });
```

/cc @davidfowl in case he'd like to add more details about the SignalR session ID thing :smile:

**Comment by antonsacz** [comment]
Thanks, it has helped!

**Comment by caleblloyd** [comment]
Parsing the `access_token` query string parameter appears to now be included by default, see https://github.com/openiddict/openiddict-core/issues/666#issuecomment-1159117487
