### ISSUE TITLE
Question on OpenidDict

### ISSUE THREAD

**Issue by soeron** [openiddict/openiddict-core#48]
Hi! Thank you for the effort you put on the project!
I am trying to achieve some sort of architecture like on the picture, which eventually will have to become on premise multiuser system.

![idsrv](https://cloud.githubusercontent.com/assets/726938/12354733/82200e5c-bba0-11e5-913a-ce37f7fe138e.jpg)

There will be any number of services which may or may not talk to each other.
WebAPIs will be consumed by different of type clients.
Clients should talk to services only.
Communication channel is standard REST.

To access different resources of those APIs they have to provide identity, which will be authorized per WebAPI basis.
To get such identity they will access API on the service which will translate the request to the IdentityProvider.
The IdentityProvider may have different sources to validate credentials - Local Users (from local DB), or ADFS connections.
The identity server will have an authentication entry point and based on the provided username it will redirect to the proper identity validator.
For example, if provided username is northwind\john it will try to validate the credentials in northwind domain. If everything is OK then the returned principal will be transformed in JWT token and returned to the WebAPI, which will return it to the client as an access token that will be used for resource access.
I am willing to use AspNet.Identity with EF to store users, their roles and such.
Obviously users should be managed on many places, but Identities and credentials only on one.

So the questions I am having are:
- Does OpenidDict fits in the architecture as IdentityProvider?
- Does it have most of the required features to use it in such architecture? (ADFS Provider, User Management etc. )

Any advices are also welcomed if you have any.

Since IdentityServer announced integration with AspNet.Identity and flawless integration with ASP.NET 5 I will ask there the same question too.

Regards,
Daniel

**Comment by kevinchalet** [comment]
> Does OpenidDict fits in the architecture as IdentityProvider?

Sure.

> Does it have most of the required features to use it in such architecture? (ADFS Provider, User Management etc. )

As mentioned in the README, the user management part is handled by ASP.NET Identity 3 itself (which includes username/password authentication and external provider association).

There's deliberately no provider-specific features in OpenIddict, as external authentication (with a well-known social provider like Google or Facebook or with your own server) can be easily implemented using the ASP.NET 5 security middleware developed by MSFT or by the community (I developed a [generic OpenID2 provider](https://github.com/aspnet-contrib/AspNet.Security.OpenId.Providers) and [many OAuth2 providers](https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers) have been added by the community).

ADFS (and by extension, Azure AD) is no exception. Depending on the exact version you're using, you'll be able to use the OIDC client middleware (Azure AD and ADFS for Windows Server 2016) or the OAuth2 generic middleware with some tweaking (ADFS 3.0). Since [ASP.NET 5 doesn't have a WS-Fed middleware](https://github.com/aspnet/Security/issues/605#issuecomment-162344309), supporting earlier versions will be tricky.

Curious: which version are you using?

**Comment by soeron** [comment]
Hi there.
Which version of what?
I am using dev branch of OpenidDict and rc2 of asp.net.
Just playing around and creating PoCs. For the ADFS I will probably want to support ADFS2, but since the intention is to target full framework, then I think it wont be such problem. There are few examples how to validate against DC using ASP.NET4 and with some tweaks managed to run on dnx451 which for now is ok for me.

Regards,
Daniel

**Comment by kevinchalet** [comment]
> Which version of what?

Of ADFS.

> For the ADFS I will probably want to support ADFS2.

So yeah, with ADFS2, it's pretty much the easiest approach.

As long as you can create a `ClaimsIdentity`/`ClaimsPrincipal` with at least a unique `ClaimTypes.NameIdentifier` claim and use Identity's `SignInManager` (or the ASP.NET 5 authentication API it uses internally) to create an authentication cookie, then it should be fine for OpenIddict.
