### ISSUE TITLE
Strong name signing issue

### ISSUE THREAD

**Issue by DavidUrting** [openiddict/openiddict-core#492]
Hello,

adding OpenIddict packages to an ASP.NET Core 2 application, that is signed with an .snk key, causes a **strong name validation failed** exception since the OpenIddict assemblies are not fully signed. 
Is it possible to sign the assemblies in future releases?

Thanks,

**Comment by kevinchalet** [comment]
Hey,

> Is it possible to sign the assemblies in future releases?

Unfortunately we can't because OpenIddict depends on an external library that is itself not strong-named: https://github.com/henkmollema/CryptoHelper.

In an old post, CryptoHelper's maintainer (@henkmollema) suggested using the [StrongNamer package](https://www.nuget.org/packages/StrongNamer/).

This is not something we can do in the OpenIddict project itself (as it would result in the OpenIddict assemblies being linked to invalid assembly references), but you can use it in your own project to work around the fact OpenIddict and CryptoHelper are not strong named.

Or you can also try to convince @henkmollema that it would be worth releasing a separate version that is strong named :smile:

**Comment by DavidUrting** [comment]
Thanks for the pointer to **StrongNamer**, it's a magic little gem I didn't knew it existed. It works now!

**Comment by henkmollema** [comment]
Dodged a bullet there! 😄

**Comment by henkmollema** [comment]
That being said, I will look into providing a strong named package of CryptoHelper. @PinpointTownes seems to like strong naming a lot. 😈

**Comment by kevinchalet** [comment]
> @PinpointTownes seems to like strong naming a lot. :smiling_imp:

Haha no, I don't. But SN is one of these viral things (like async and generics :sweat_smile:). If we don't sign our assemblies, folks that use them have to do that themselves ; tho' I agree it's no longer painful these days, thanks to build tools like StrongNamer.

**Comment by kevinchalet** [comment]
> That being said, I will look into providing a strong named package of CryptoHelper.

If you do that, please let me know. OpenIddict RC1 is about to be pushed to NuGet.org, so that might be the occasion (note that we'd need both an ASP.NET Core 1.0.0 and 2.0.0-compatible version).

**Comment by kevinchalet** [comment]
@henkmollema since you're not a huge fan of strong naming (for reasons I definitely understand and respect), would providing a "sources" package of `CryptoHelper` be a better option for you?

`CryptoHelper` has a single class/file, which makes it an excellent candidate for that (it's a pattern massively used by the ASP.NET folks: https://github.com/aspnet/Common/tree/dev/shared).

**Comment by kevinchalet** [comment]
@henkmollema ping.

**Comment by henkmollema** [comment]
Whoops, forgot about this. 😅 
I'll try and look into this tomorrow.

**Comment by kevinchalet** [comment]
@henkmollema thanks, I really appreciate :+1:

**Comment by henkmollema** [comment]
@PinpointTownes I've just uploaded [CryptoHelper](https://www.nuget.org/packages/CryptoHelper.StrongName). I'll send a PR shortly.
