### ISSUE TITLE
OpenIddict aims at providing a simple and easy-to-use solution

### ISSUE THREAD

**Issue by bastienJS** [openiddict/openiddict-core#505]
What other STS did you have in your mind writing that? :-> Good that you did not wrote 'more secure' :P

Seriously... I really would be interested why your implementation is more easier/simpler than e.g. IdentityServer4.

Would you mind share your thoughts. I have read once on SO that someone asked the same but you meant it would be opiniated... well but here on your place everything is allowed :-)

**Comment by kevinchalet** [comment]
> What other STS did you have in your mind writing that?  :-> 

If I wanted to compare it to another OIDC server project, I'd say "simpler/easier-to-use than X, Y, Z" or "simplest and easiest-to-use", not just "simple and easy-to-use" :smile: 

> Good that you did not wrote 'more secure' :P

That would be pretentious. While I've tried my best to take the OAuth2 threat model into account and even if no vulnerability has been reported so far in OpenIddict (or in the underlying OIDC server middleware), I know it's only a matter of time (even IdSrv is not perfect as a XSS vulnerability was recently found in IdSrv3).

> Would you mind share your thoughts.

As the developer/maintainer of this project, it's hard to be objective.

I think it's simple because it takes care of most the gnarly protocol details for you (e.g client authentication, request validation, token encryption/signing) and only leaves the user authentication and claims generation parts as an exercise, as these are the two parts you'll want to configure yourself to match your exact business needs (and for that, you can use Identity, a custom membership provider, a remote authentication service or whatever else you want).

It's also (quite) easy to use because you only have to add the OpenIddict references, register the OpenIddict services in the container and copy/paste the authorization controller corresponding to the flow(s) you want to support.

Now, don't count on me to say that OpenIddict is better (or worse :sweat_smile:) than Identity Server. Both are cool projects, made with love by their respective developers :smile:

Give them a try and let us know what you think.

**Comment by Bartmax** [comment]
@bastienJS also, this project start because some, ehem, people were very vocal about the pain points in the OIDC protocol, the current state of libraries/helpers and the not existing straightforward path for most general usage (like with EF and Identity). It's not about easier than X or Y.
So the main goal of this library was to solve the "hard and complex" problem.

@PinpointTownes taken the feedback and using his vast experience on the field, he were tweaking and improving taking into consideration lot of nits and very minor details to increase the ease of use, even if it were very minor.

If OpenIddict is not "easy and simple", this would be a failed project, from my experience it's a huge success, and I do have a lot of respect and ❤️  for this maintainer and library. 

Hope it helps address your question.

**Comment by a-patel** [comment]
how to use OIdC with custom user and role tables (i.e. without asp.net identity tables)??

I want to use in Asp.Net Core 2.x

**Comment by kevinchalet** [comment]
> how to use OIdC with custom user and role tables (i.e. without asp.net identity tables)??

http://kevinchalet.com/2017/01/30/implementing-simple-token-authentication-in-aspnet-core-with-openiddict/

**Comment by a-patel** [comment]
thanks @PinpointTownes

**Comment by kevinchalet** [comment]
@bastienJS closing as I believe we answered your question. If not, feel free to re-open.

**Comment by bastienJS** [comment]
Thanks for your answer!
