### ISSUE TITLE
Doesnt work on Local IIS, found bug...

### ISSUE THREAD

**Issue by Gillardo** [openiddict/openiddict-core#52]
This has caused me a right headache, but there seems to be a problem with OpenIddict.  I added all this code to my application, and it worked perfectly using the `dnx web` command, and also if i run my code using IISExpress.  But if i upload this to my web server running IIS, the site never loaded.

My site is setup, like a normal basic site, i have an applicationPool which is running using the IIS POOL/XXX account specific for that site.

The reason that the site never loaded, was because OpenIddict, seems to create a [GUID].key file in the wwwroot of the published site.  Because my IISPOOL/XXX user doesnt have write permission to the wwwroot folder (which i dont think it should), this process failed.

Have i setup something wrong?  Should i have stated something in my startup.cs file to write this file to another place??

**Comment by kevinchalet** [comment]
> The reason that the site never loaded, was because OpenIddict, seems to create a [GUID].key file in the wwwroot of the published site. Because my IISPOOL/XXX user doesnt have write permission to the wwwroot folder (which i dont think it should), this process failed.

When you don't explicitly register a signing key, one is automatically created and persisted for you on the disk (in the AppData folder or in the current directory if the user profile is not available).

Last week, I pushed a commit to replace the last fallback value to use the TEMP directory instead of the current directory, so the "bug" you're seeing should disappear when updating your packages: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/commit/f22d2ea360311b6db193c308e928ceedc84c67d1

> Have i setup something wrong? Should i have stated something in my startup.cs file to write this file to another place??

Using a X509 certificate stored in the machine store is recommended for production environments:

``` csharp
app.UseOpenIddict(builder => {
    builder.Options.SigningCredentials.AddCertificate("thumbprint");
});
```

You can also load it from a file:

``` csharp
app.UseOpenIddict(builder => {
    builder.Options.SigningCredentials.AddCertificate(new X509Certificate2("path", "password"));
});
```

**Comment by Gillardo** [comment]
@PinpointTownes Thanks for this, this works perfectly

**Comment by kevinchalet** [comment]
Nice! :clap:
