### ISSUE TITLE
Expose collection properties as real collections on model types

### ISSUE THREAD

**Issue by xperiandri** [openiddict/openiddict-core#579]
Now you have ISet properties only on descriptor.
Let's add them publicly to model type and hide current string properties privately. Then EF will set private property and we will deserialize them from JArray to a HashSet back.

**Comment by xperiandri** [comment]
``` C#
public class TenantApplication : OpenIddictApplication<Guid, TenantAuthorization, TenantToken>
{
    internal static readonly string AllowedTenantsStoreName = nameof(AllowedTenantsStore);

    private string allowedTenantsStore;

    private string AllowedTenantsStore
    {
        get => JArray.FromObject(allowedTenants).ToString();
        set => allowedTenantsStore = value;
    }

    private string[] allowedTenants;

    public string[] AllowedTenants
    {
        get => allowedTenants ?? (allowedTenants = JArray.Parse(allowedTenantsStore)
                                                         .Values<string>()
                                                         .ToArray());
        set => allowedTenants = value;
    }
}
```

``` C# 
builder.Entity<TenantApplication>(entity =>
{
    entity.PrivateProperty<string>(TenantApplication.AllowedTenantsStoreName)
          .HasColumnName("AllowedTenants");
});
```

``` C#
internal static class DbContextExtensions
{
    internal static PropertyBuilder<TProperty> PrivateProperty<TProperty>(this EntityTypeBuilder builder, string propertyName)
    {
        var propertyBuilder = builder.Property<TProperty>(propertyName);
        if (propertyBuilder.Metadata.IsShadowProperty)
        {
            throw new ArgumentException($"Property {propertyName} was not found on {builder.Metadata.Name}");
        }
        return propertyBuilder;
    }
}
```

**Comment by kevinchalet** [comment]
Is there a particular reason why you'd want to use the "stringified" properties instead of the accessor exposed by the application manager?

I'm not opposed to adopt this pattern (even if the code is a bit ugly). But we'll face an issue: our stores uses the "stringified" properties in LINQ queries. E.g: https://github.com/openiddict/openiddict-core/blob/dev/src/OpenIddict.Core/Stores/OpenIddictApplicationStore.cs#L205-L213

**Comment by xperiandri** [comment]
Ah, you now expose methods on ApplicationManager to read and validate and on ApplicationStore to also set such parameters.
Well not bad in general.

Then let's wait EF Core 2.1. It will be more useful to just set converters for this properties.
Going such a long way with methods looks not very continent, doesn't it?

**Comment by xperiandri** [comment]
I just wonder how to move evaluation of such properties to DB.

**Comment by kevinchalet** [comment]
> Going such a long way with methods looks not very continent, doesn't it?

OpenIddict works this way since day 1. This pattern is inspired from ASP.NET Core Identity and allows writing components that don't depend on a particular model type.

In OrchardCore, this is what allows us to create controllers that work the same way independently of the stores chosen by the user: the default YesSql stores use their own models - completely optimized for the document-oriented nature of YesSql - and the EF Core stores have models that inherit from OpenIddict's default entities.

**Comment by kevinchalet** [comment]
Note: the layering should be clearer once https://github.com/openiddict/openiddict-core/pull/580 is merged.
