### ISSUE TITLE
Authentication pipeline does not checking OpenIddictAuthorization status "revoked"

### ISSUE THREAD

**Issue by Sensarg22** [openiddict/openiddict-core#600]

**Comment by kevinchalet** [comment]
That's intentional. The idea is that revoking an authorization doesn't affect the associated tokens but is only a hint you can use for future authorization requests (e.g [to avoid having to re-display a consent form](https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Modules/OrchardCore.OpenId/Controllers/AccessController.cs#L100-L105)). To prevent the tokens associated with a revoked authorization, you must also revoke the tokens using `OpenIddictTokenManager.RevokeAsync()`.

That said, I'm not opposed to change that if there's enough demand.
