### ISSUE TITLE
Get call to /.well-known/jwks fails resulting in an infinite loop

### ISSUE THREAD

**Issue by davidtimovski** [openiddict/openiddict-core#606]
My site is hosted on Ubuntu 16.04 with nginx as a reverse proxy. This started happening to me once I started hosting my site with HTTPS and started using redirects.

My aurelia app, which uses [aurelia-open-id-connect](https://github.com/aurelia-contrib/aurelia-open-id-connect) and 2.0.0-rc2 of OpenIddict at some point makes an HTTP (not HTTPS) call to `/.well-known/jwks` which fails with blocked:mixed-content.

I've set `options.DisableHttpsRequirement();` because I'm using SSL with nginx so I don't need it for Kestrel. I'm under the impression that the flag is the reason why that call is being made with HTTP instead of HTTPS and thus results in the failed call and never-ending loop.

All of the other calls are HTTPS because they're dependent on the URLs I've set for my Application.

I'm not sure I completely understand the issue but maybe you do.

**Comment by kevinchalet** [comment]
My recommendation is to avoid using `options.DisableHttpsRequirement()` (that simply consists in not rejecting HTTP requests). Instead, consider fixing your app so that the ASP.NET Core components know that the request was made using TLS, even if the communication between nginx and Kestrel was made without transport security.

Read https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-2.0&tabs=aspnetcore2x#configure-a-reverse-proxy-server for more information.

**Comment by davidtimovski** [comment]
Okay so I had went through that article you linked when I initially setup for nginx but didn't pay too much attention to the [Configure ASP.NET Core to work with proxy servers and load balancers](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-2.0) link.

Specifically the code in [this part](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-2.0#when-it-isnt-possible-to-add-forwarded-headers-and-all-requests-are-secure) fixed the issue for me. I've removed `options.DisableHttpsRequirement();` now.

Thank you.
