### ISSUE TITLE
UseOpenIdDict<TKey> vs ReplaceDefaultEntities<TKey>

### ISSUE THREAD

**Issue by 1619digital** [openiddict/openiddict-core#614]
I'm wondering whether there's a certain redundancy here in defining the key type for the OpenIddict entities? Seems it has to be set in both places.

For the former the comments say

>                 // Register the entity sets needed by OpenIddict.
>                 // Note: use the generic overload if you need
>                 // to replace the default OpenIddict entities.

... (which is quite clear) but that seems to be what the second method is doing to? Thanks.

**Comment by kevinchalet** [comment]
We can call that redundancy (which is mostly [due to historial reasons](https://github.com/aspnet/EntityFrameworkCore/issues/7185)), but it's worth mentioning the 2 methods actually configure 2 different things:
  - The EF Core `options.UseOpenIddict<TKey>()` registers the OpenIddict EF Core models in the `DbContext` using the specified key type.

  - `options.UseEntityFrameworkCore().ReplaceDefaultEntities<TKey>` configures [the OpenIddict core components to use the OpenIddict EF Core models with the specified key as the default entities](https://github.com/openiddict/openiddict-core/blob/dev/src/OpenIddict.Core/OpenIddictCoreOptions.cs#L16-L38), used by the server and validation services.

In 2.0, we could certainly remove the generic EF Core `options.UseOpenIddict<TKey>()`/``options.UseOpenIddict<[models + key type]>()`` extensions and force EF Core to use the default entities configured via `ReplaceDefaultEntities<TKey>`.

**Comment by 1619digital** [comment]
Ok many thanks. Just thought I'd draw attention to it - it caught me out because I was thinking "I've already set this". Most importantly, when all set properly, everything's functioning as expected.

Feel free to close.
