### ISSUE TITLE
Why not make ConcurrenyToken generic?

### ISSUE THREAD

**Issue by xperiandri** [openiddict/openiddict-core#633]
If it is a GUID, then I would better use UNIQUEIDENTIFIER column for it in database

Then it will have default stringified GUID in string representation only.

**Comment by kevinchalet** [comment]
Because we'd need another generic parameter in the entities and in the stores definitions. I really don't think it's worth the added complexity. If you don't like the `ConcurrencyToken` - that is exactly the same as the method used in ASP.NET Core Identity - ignore it in the EF Core context and use your own property/column.

**Comment by xperiandri** [comment]
Then make it as shadow property.
Do you need it explicitly?

**Comment by kevinchalet** [comment]
We could certainly move to a shadow property but it would be way more painful to set it and declare it as a concurrency check property using the EF Core model builder. I don't see a good reason to make this change.

FWIW, ASP.NET Core Identity has the same property in all their models. Have you contacted them to remove this property? :trollface:

**Comment by xperiandri** [comment]
Agree. They introduced this ugly workaround
