### ISSUE TITLE
problem in OpenIddictConstants inside NuGet packages 2.0.0-rc3-final

### ISSUE THREAD

**Issue by mastrox** [openiddict/openiddict-core#659]
Hi
I have followed the getting started tutorial:
i've linked the NuGet packages 
`<PackageReference Include="OpenIddict" Version="2.0.0-rc3-final" />`
`<PackageReference Include="OpenIddict.EntityFrameworkCore" Version="2.0.0-rc3-final" />`

 i have added the sample AuthorizationController to my app, the code don't compile because it seem to be missing some constants and clsses in OpenIddictConstants:
it miss Erros class, it miss all the constant other than Roles from OpenIddictConstants.Claims ecc..

I've tried to link directly the dll builded from the source code and the class OpenIddictConstants has all the missing thing.

**Comment by kevinchalet** [comment]
Hey,

The samples in this repository use the latest OpenIddict bits, and the not the packages published on NuGet.org. The new constants have been introduced in the RTM nightly builds and that's why you can't use them when targeting RC3. In RC3, you can find them in the `OpenIdConnectConstants` class. In RTM, we copied them to `OpenIddictConstants` for convenience.

You can find the samples for RC3 here: https://github.com/openiddict/openiddict-samples
