### ISSUE TITLE
Question/Implementation Detail - Authorization Handler Redirect on existing Authorization?

### ISSUE THREAD

**Issue by schmitch** [openiddict/openiddict-core#665]
Hello, currently I'm not sure if this is correct and I'm also not sure if this is a question or if the examples should be updated or if it is plain invalid.

However currently if I try the sample `Mvc.Server` with `Mvc.Client` or even the `Postman` example with the grant_type=authorization_code it will **always** create a new authorization + request after a user was logged out manually or automatically via cooky sliding.

**But** I think the correct implementation should re-use existing authorization's, by checking the Authorization Table and if there is a `valid` Authorization with the corresponding Token it should actually short circuit the Authorization and instead redirect to `~/connect/token`, something like:

```
 // FIXME: implement FindByApplicationAndScopes
var authorization = await _authorizationManager.FindByApplicationAndScopes(...)
if (authorization != null)
{
    return Redirect("/connect/token...") // FIXME: add params
}
```

currently I think "most" servers do it like that (and one big contender is google):

```
i.e.:
* https://developers.google.com/identity/protocols/OAuth2WebServer#userconsentprompt
* https://developers.google.com/identity/protocols/OpenIDConnect#re-consent
* https://stackoverflow.com/a/14929345/2250209

I think at least an example, how to do it should be given and probably add some easier methods to AuthorizationManager to check if the Scopes and Application combination already has consent.

(if you like the idea, I would probably try to add a PR)

**Comment by kevinchalet** [comment]
Hey,

> But I think the correct implementation should re-use existing authorization's, by checking the Authorization Table and if there is a valid Authorization with the corresponding Token it should actually short circuit the Authorization and instead redirect to ~/connect/token, something like:

Redirecting your users to the token endpoints: no, as it's basically an API endpoint made to be used by non-interactive clients so that they can redeem an authorization code for an access token.

But yeah, immediately returning an authorization response when your users have already approved the application is a very common scenario, as you said.

OpenIddict has already everything you need to achieve that. If you're looking for some real world code, take a look at OrchardCore's OpenID module:
  - It supports implicit (trusted apps), explicit (non-trusted apps) and external (pre-approved) consents.
  - It uses the authorization manager to determine whether a permanent authorization already exists for the requested scopes.
  - It creates permanent authorizations once the application is approved so that OpenIddict doesn't fall back to its "one-per-authorization-request ad-hoc authorizations" logic.

https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Modules/OrchardCore.OpenId/Controllers/AccessController.cs#L96-L131

https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Modules/OrchardCore.OpenId/Controllers/AccessController.cs#L435-L454
