### ISSUE TITLE
Refresh token renew flow

### ISSUE THREAD

**Issue by ddydeveloper** [openiddict/openiddict-core#677]
Morning! Just want to confirm the right way of the refresh token usage. 

As I understand from the version 2 we should enable the UseRollingTokens option to get a new refresh_token (every access_token refresh request using refresh_token flow) and revoke an old one. It was by default for the version 1.

A question is how to manage multiple async queries to the API in case when one of them renew the refresh_token and other try to use the existing one (they will get an error about invalid refresh_token).

It is less about the openiddict implementation and more about the oidc in general, but anyway is it correct to implement something like retry pattern for the failed queries?

Are there any bottlenecks for the openiddict according to considered approach?

**Comment by kevinchalet** [comment]
Hey,

My recommendation is to avoid using rolling tokens when you know your clients are likely to send concurrent requests, as indicated in https://github.com/openiddict/openiddict-core/issues/462.

If you absolutely want to use rolling tokens, then you'll indeed have to write some synchronization logic to ensure all the instances of your apps don't try to redeem the same refresh token at the same time (otherwise, there's a race condition and only a few of them may get a valid response).

**Comment by ddydeveloper** [comment]
I am agree that it is a good decision if we are talking about the concurrent token requests.

But what about the refresh token lifetime, is it really securely to have just single token?

**Comment by kevinchalet** [comment]
https://github.com/openiddict/openiddict-core/issues/462#issuecomment-330270543
