### ISSUE TITLE
Why do we need to provide clientId/clientSecret in password flow ?

### ISSUE THREAD

**Issue by jonathanantoine** [openiddict/openiddict-core#701]
In my understanding of OpenId Connect, when I choose the password flow, I should be able to provide only the clientId without clientSecret (not secure storage in my case). Is it possible without disabling ClientId Verification as a whole ?

**Comment by kevinchalet** [comment]
It's only possible if your client application is declared as a public client. In this case, there's no client secret, and the request will be considered valid if the `client_id` is sent (and valid, obviously).

Such a thing is not possible for confidential clients: if you omit the client secret in this case, an error is returned, stating that the client secret was missing (otherwise, there would be no point having public vs confidential clients).

**Comment by jonathanantoine** [comment]
Thanks for answering me. How can I set a client application as public ?

**Comment by kevinchalet** [comment]
Simply don't set a client secret when creating your app using the app manager and it will create a public client. If you want things to be explicit, you can set `OpenIddictApplicationDescriptor.Type` to `OpenIddictConstants.ClientTypes.Public`.

**Comment by jonathanantoine** [comment]
Merci @PinpointTownes, that was the missing part in my mind :)
