### ISSUE TITLE
Prune and LifeTime- when is this executed ?

### ISSUE THREAD

**Issue by auriou** [openiddict/openiddict-core#734]
Hello, 
I would like to know when PruneAsync functions are executed to purge the base of the old token and authorization ?

And what are the following variables for ?

````
            ticket.SetAuthorizationCodeLifetime(TimeSpan.FromMinutes(1));
            ticket.SetIdentityTokenLifetime(TimeSpan.FromMinutes(30));
````
Is it only for purging?

Thx

**Comment by kevinchalet** [comment]
Hey,

> I would like to know when PruneAsync functions are executed to purge the base of the old token and authorization ?

Currently, never: it's something you have to do yourself (e.g in a cron-based Azure Function).
https://github.com/openiddict/openiddict-core/issues/361 tracks future improvements for automatic pruning.

> And what are the following variables for ? Is it only for purging?

"only", no, the lifetime assigned to a token type also directly impacts the validation stage, since expired tokens will be rejected.

**Comment by auriou** [comment]
Thank you Kevin.
