### ISSUE TITLE
Problem with validation of Urls

### ISSUE THREAD

**Issue by HesamKashefi** [openiddict/openiddict-core#742]
Hi,
When the client apps send their redirectUri and postLogoutUri , ... we always face a very simply problem which is :
if the urls are stored in the database like this : `https://www.github.com` and the client sends `https://www.github.com/` that ending slash makes the validations fail!
I wanted to know is this an intended behavior?
The problem is the deploy team configures urls in config files ... .

**Comment by kevinchalet** [comment]
Hey,

Yes, it's the expected behavior: the OpenID Connect specification requires doing "simple string comparisons" (as defined in https://tools.ietf.org/html/rfc3986#section-6.2.1) without any URI normalization.

I'd recommend registering both `https://www.github.com` and `https://www.github.com/` if the two are used.

**Comment by HesamKashefi** [comment]
Great, Thanks.
