### ISSUE TITLE
Using entiyframework custom execution strategy is not possible

### ISSUE THREAD

**Issue by nurhat** [openiddict/openiddict-core#748]
Due to user initiated transactions in  OpenIddict.EntityFrameworkCore, we are not able to use  custom execution strategies [link](https://docs.microsoft.com/en-us/ef/ef6/fundamentals/connection-resiliency/retry-logic#user-initiated-transactions-are-not-supported). There should be a configuration to enable usage of custom execution strategies. 

Best Regards
Nurhat

**Comment by kevinchalet** [comment]
Places where we use transactions in the EF Core stores are fairly rare (they are typically used for delete and pruning operations, since we can't use cascade deletes due to the circular nature of the OpenIddict entities).

Can't you just suspend the execution strategy prior to invoking the OpenIddict managers?
