### ISSUE TITLE
Getting a refresh token for offline access

### ISSUE THREAD

**Issue by courtenayparserr** [openiddict/openiddict-core#751]
I'm busy using the authorization sample to make requests to an authorized endpoint.

Of course these tokens expire and so I get:

![image](https://user-images.githubusercontent.com/24819057/60145993-2b4c6580-980b-11e9-90ef-7f0f7eda5f46.png)

How do i setup the authorizationcontroller to accept a refresh request?
How do I allow offlineaccess to occur? I've done the following in the startup.cs:
![image](https://user-images.githubusercontent.com/24819057/60146086-87af8500-980b-11e9-94bc-bd1ab7c3e250.png)

How do i make the refresh request when the token has expired?

It wasn't apparent to me in the Angular example...

**Comment by courtenayparserr** [comment]
It is similar to this question here:

https://stackoverflow.com/questions/55282896/openiddict-code-flow-handling-access-token-expiration

**Comment by kevinchalet** [comment]
Here's the client code responsible of sending the refresh token request - which is nothing more than a simple API request with a few parameters: https://github.com/openiddict/openiddict-samples/blob/dev/samples/RefreshFlow/AngularApp/src/core/auth.service.ts#L99-L119

It matches what the specification describes here: https://tools.ietf.org/html/rfc6749#section-6

That said, since you're using the code flow in an Angular app, you may want to avoid using refresh tokens and instead rely on "silent authentication", that involves sending `prompt=none` authorization requests in an iframe.

You can find an example in the implicit flow demo project (but it works the same way with the code flow):

  - https://github.com/openiddict/openiddict-samples/blob/dev/samples/ImplicitFlow/AuthorizationServer/Controllers/AuthorizationController.cs#L48-L65

  - https://github.com/openiddict/openiddict-samples/blob/dev/samples/ImplicitFlow/AureliaApp/src/home.ts#L71-L78

**Comment by greendimka** [comment]
> Here's the client code responsible of sending the refresh token request...

The links are broken here

**Comment by kevinchalet** [comment]
> The links are broken here

It's an almost 4-year-old thread...

Up-to-date samples can be found in the samples repository: https://github.com/openiddict/openiddict-samples.

**Comment by greendimka** [comment]
Hi, Kévin, thanks for the fast response.
I came to this thread because I did not get the refresh token for the offline access, though using v. 4.3.0. with the password flow.
