### ISSUE TITLE
Database don't support datetimeoffset type

### ISSUE THREAD

**Issue by lucazoffoli** [openiddict/openiddict-core#753]
Hi,
My database don't support DateTimeOffset, so I create table OpenIddictTokens with CreationDate and ExpirationDate as DateTime.
Is Possible override a OpenIddictTokenStore to use DateTime instead of DateTimeOffset?
Other solutions? (I can't upgrade my database...)

**Comment by jeremycook** [comment]
@lucazoffoli As a random passerby, I'm curious what database and version of said database are you using? DateTimeOffset has been around since SQL Server 2008.

**Comment by lucazoffoli** [comment]
@jeremycook Unfortunately sql server 2005...

**Comment by jeremycook** [comment]
@lucazoffoli is it due to 3rd party hosting or are you hosting on premises? 

If you are on prem I would recommend standing up SQL Server Express. It would likely be powerful enough to cover your needs as an auth server database, is free to use and totally legal to use for any purpose. The main limitations of Express are memory footprint and database file size. 

If you're using 3rd party hosting this might be an opportunity to look at 3rd party hosts that provide SQL Server that is still supported by Microsoft.

Also, if this is some crazy management decision then I would consider this an opportunity to push back. It really isn't the best security posture to use software that has reached end of life and hasn't been supported or updated since [April 2016](https://www.microsoft.com/en-us/sql-server/sql-server-2005)... All the more important in this case, considering that OpenIddict is an electronic security system.

**Comment by kevinchalet** [comment]
I completely agree with @jeremycook 😄 

That said, if you absolutely can't migrate to a different host, you could copy the EF Core stores and models and update them to use `DateTime` instead of `DateTimeOffset`. It's trivial and that's what we do in the MongoDB stores (to ensure we have the best BSON representation possible for dates):

  - https://github.com/openiddict/openiddict-core/blob/dev/src/OpenIddict.MongoDb/Stores/OpenIddictTokenStore.cs#L453
  - https://github.com/openiddict/openiddict-core/blob/dev/src/OpenIddict.MongoDb/Stores/OpenIddictTokenStore.cs#L793

**Comment by lucazoffoli** [comment]
Ok, thanks for your replies. :)
@jeremycook
@PinpointTownes
