### ISSUE TITLE
Possible bug with remote packages

### ISSUE THREAD

**Issue by stefan505** [openiddict/openiddict-core#86]
1) Clone https://github.com/stefan505/openiddict-core
2) Run `Mvc.Server` using `dotnet run`
3) Register user
3) Use PostMan to sign in using user : `http://localhost:5000/connect/token`
4) Get `access_token` and append to auth header and call `http://localhost:5000/api/message`

Result is 401 

Now change from `"OpenIddict": "1.0.0-alpha2-0214"` to `"OpenIddict": "1.0.0-alpha2-0216"` and re-perform all steps and it works.

**Comment by kevinchalet** [comment]
Nothing changed between OpenIddict `1.0.0-alpha2-0214` and `1.0.0-alpha2-0216`, except its dependencies: ASOS and the validation middleware were recently updated to use different data protection strings than the ones we were previously using.

As long as you're using compatible ASOS/validation middleware versions, it should work fine.
Due to the (stupid, IMHO) "lowest applicable version" dependencies resolution rule of NuGet 3, a weird mismatch occurred here:

Using `1.0.0-alpha2-0216` forced dnu/dotnet restore to use the latest ASOS package, since it's the minimal version targeted by `OpenIddict.Core`'s nuspec and that's why it worked fine:

```
<dependency id="AspNet.Security.OpenIdConnect.Server" version="[1.0.0-beta5-0687, )" />
```

`1.0.0-alpha2-0214` lists an older ASOS version, so dnu/dotnet restore used it despite a newer version being on the aspnet-contrib feed.

Since the validation middleware is listed as a floating dependency by the Mvc.Server sample, the latest package is always downloaded. Yet, using an old ASOS package with the latest validation middleware can't work, due to the data protection strings changes.

Luckily, using the latest OpenIddict package should fix this NuGet hell.

**Comment by stefan505** [comment]
Thanks @PinpointTownes, that explains what happened then. Will note this kind of behavior going forward for future reference.
