### ISSUE TITLE
dotnet build does not create exe

### ISSUE THREAD

**Issue by nicolasr75** [openiddict/openiddict-core#90]
First of all: thanks so much for this great work! It is amazing how seamlessly this works and how much care you took for a great sample and good documentation.

My problem is with publishing a server project, either self-hosted or IIS.
The sample web.config shows this:
`<aspNetCore processPath=".\Mvc.Server.exe"`
The problem is that neither _dotnet build_ nor _dotnet publish_ produce an exe. They only spit out a dll. What could be the problem here? I thought dotnet cli was supposed to create exe files.

My current environment is:

.NET Command Line Tools (1.0.0-rc2-002426)

Product Information:
 Version:     1.0.0-rc2-002426
 Commit Sha:  08ee6dedd9

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

thanks, Nicolas

**Comment by kevinchalet** [comment]
> First of all: thanks so much for this great work! It is amazing how seamlessly this works and how much care you took for a great sample and good documentation.

Thanks for the kind words :smile: 
ATM, there's no real documentation, but that's something we'll address in the future.

> The problem is that neither dotnet build nor dotnet publish produce an exe. They only spit out a dll. What could be the problem here? I thought dotnet cli was supposed to create exe files.

Hum, that's a good question. Actually, the fact it doesn't produce an .exe doesn't seem surprising, since all our samples use the shared runtime model, which offers a similar approach to DNX (it's the approach used by all the ASP.NET Core samples, AFAIK).

TBH, I haven't tested the IIS integration yet, since it relies on the whole new `AspNetCoreModule`, which requires some heavy changes in the IIS configuration file to work.

I'll ping @Guardrex tomorrow to make sure we have the right artifacts for the IIS integration to work correctly, but in the meantime, I'd recommend avoiding using IIS and directly using Kestrel:

Mvc.Client: `dotnet run server.urls=http://localhost:53507/`
Mvc.Server: `dotnet run server.urls=http://localhost:54540/`

**Comment by kevinchalet** [comment]
@Guardrex yo! Do you happen to know if these items are required for the IIS integration to work? https://github.com/aspnet/cli-samples/blob/master/HelloMvcApi/project.json#L24-L32

**Comment by guardrex** [comment]
@PinpointTownes Yeah ... if it's going to be shared, then use a diff `processPath` and `arguments` in https://github.com/openiddict/openiddict-core/blob/dev/samples/Mvc.Server/web.config#L7 ...

Use ...

``` xml
<aspNetCore processPath="dotnet" arguments=".\Mvc.Server.dll" stdoutLogEnabled="false" 
stdoutLogFile=".\logs\stdout" forwardWindowsAuthToken="false" />
```

... and the server will need the `AspNetCoreModule` ...
[AspNetCoreModule x64 MSI Installer](http://download.microsoft.com/download/7/2/D/72DD68D5-7386-4A41-8B8F-E21779A69E33/aspnetcoremodule_x64_en.msi)
... OR ...
[AspNetCoreModule x86 MSI Installer](http://download.microsoft.com/download/7/2/D/72DD68D5-7386-4A41-8B8F-E21779A69E33/aspnetcoremodule_x86_en.msi)

... and will need the [.NET Core Installer](https://github.com/dotnet/cli/tree/rel/1.0.0) ... to install the shared framework on the server.

That should work ... in theory ... of course :wink: ... pray to the :pray: server gods :pray: and sacrifice a Logitech mouse. It should work.

**Comment by guardrex** [comment]
@PinpointTownes ^^ No, on the `publish-iis` tool ... you have the `web.config` file in your project and set in the `content` section of `project.json` to be published with the app output. Therefore, you can go without Pawel's `publish-iis` tooling.

HOWEVER ... he did build that tooling to produce the `web.config` file for you with the proper entries for `processPath` and `arguments`. You could do this: Put his tool in the app as you see there in the sample. Delete the `web.config` from your project. Remove `web.config` from the `content` section of `project.json`. When the post-publish script runs the tool, it will (a) detect no `web.config` in the project and go ahead and make one, and (b) detect that this is a shared framework app and put the correct `processPath` and `arguments` in the `web.config` for you.

**Comment by kevinchalet** [comment]
@GuardRex alright, thanks for the precious info. Per your suggestion, I'll remove the web.config files from the samples and add the uber cool IIS tool :smile: 

Am I right thinking this tool will be automagically executed by the VS tooling when targeting IIS Express? :smile:

**Comment by kevinchalet** [comment]
> ... sacrifice a Logitech mouse. It should work.

Oh no, I love mine :cry:

**Comment by guardrex** [comment]
`dotnet cli` will trigger the tooling **only** on post-publish, so you have to run the `dotnet publish` command to get the tool to run. Therefore, it won't fire off on a `dotnet build` or `dotnet run`.

The only "catch" with the tool is that Pawel shot down my idea to have custom settings for the `web.config` it generates. For example, his default `web.config` will be produced with the module log set to `false` by default (the way you have your `web.config` set now). If that's ok, cool. Otherwise, you have to leave a `web.config` in the project that the tool will merely modify ... not replace. You can set up your own `web.config` with logging set to `true`, and the tool will honor the setting. In that case, it just takes your file and modifies the `processPath` and `arguments` and shoots it into the published output.

I think you'll be fine. The `web.config` you had matches Pawel's default settings, so you can go ahead and delete the file from your project and just let the tool create it from scratch for you.

... and you are not going to sacrafice that mouse ... then the :pray: server gods :pray: may cause your app to :boom: ... **YOU HAVE BEEN WARNED PAGAN!**

**Comment by nicolasr75** [comment]
I gave this a first try. Publishing is fine and calling it from IIS too but adding OpenIddict fails

`2016-04-22 16:03:17.329 +02:00 [Error] System.UnauthorizedAccessException: Access to the path 'C:\WINDOWS\system32\config\systemprofile' is denied.
   at System.IO.Win32FileSystem.CreateDirectory(String fullPath)
   at System.IO.DirectoryInfo.Create()
   at Microsoft.AspNetCore.Builder.OpenIdConnectServerExtensions.UseOpenIdConnectServer(IApplicationBuilder app, OpenIdConnectServerOptions options)
   at Microsoft.AspNetCore.Builder.OpenIddictExtensions.<>c__DisplayClass5_0.<UseOpenIddictCore>b__0(IApplicationBuilder map)
   at Microsoft.AspNetCore.Builder.OpenIddictExtensions.UseOpenIddictCore(IApplicationBuilder app, Action1 configuration)
   at Microsoft.AspNetCore.Builder.OpenIddictExtensions.UseOpenIddict(IApplicationBuilder app, Action1 configuration)
   at MyIdentityServer.Startup.Configure(IApplicationBuilder app, ILoggerFactory loggerFactory)`

Any idea what I am missing?

**Comment by kevinchalet** [comment]
You can read https://github.com/openiddict/openiddict-core/issues/52#issuecomment-173933098 for more information.

Looks like the existing fix didn't completely solve this issue. I'll push a new one, with some try/catch to handle that.

**Comment by nicolasr75** [comment]
@PinpointTownes Ok, thanks, using an explicit certificate fixed it. So I can confirm that it works with IIS and newest dotnet cli
Product Information:
 Version:     1.0.0-rc2-002485
 Commit Sha:  d3c65aee87

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

I think it would make using OpenIddict still easier when there were a few lines showing how to create a certificate and loading it on the github start page and/or in the sample. In my case I actually used a test certificate and the according code from an IdentityServer sample. Without that it would haven taken me much more time to find out how to do it.

**Comment by kevinchalet** [comment]
Good idea, I'll add a few words in the README.md.

FYI, the `UnauthorizedAccessException` you were seeing should now be caught in the latest bits.

**Comment by nicolasr75** [comment]
Great! Then I can now proceed to actually using OpenIddict and find out what to do with it ;-)
