### ISSUE TITLE
OpenIdConnect 2.0: how to override HandleAsync when validating request contet-type at OpenIddictServerAspNetCoreHandlers.cs

### ISSUE THREAD

**Issue by gonzaloluna** [openiddict/openiddict-core#907]
Hi there, I would like to understand if there's a way to override how requests are validated during a token request. It seem's there's a handle event in the class ExtractGetOrPostRequest at OpenIddictServerAspNetCoreHandlers.cs which validates the Content-Type of the request, among other things. 

Is this possible? I dig this trying to override OpenIdConnectServerProvider but had no luck.

Thanks,

**Comment by kevinchalet** [comment]
Hey,

Yes, it's possible, but only in OpenIddict 3.0 (thanks to its more advanced events model, that gives you more control than in previous versions).

For that, you'll need to remove the default handler by calling `options.RemoveEventHandler(OpenIddictServerAspNetCoreHandlers.ExtractPostRequest<ExtractTokenRequestContext>.Descriptor)`. Then, you'll need to create your own handler and register it in the pipeline using `options.AddEventHandler()`. Consider using the same order so that your custom handler is registered at the same position in the pipeline as the "official" event handler it replaces.

Out of curiosity, why do you need to relax that? Are you dealing with non-standard clients?

**Comment by gonzaloluna** [comment]
Hi Kevin, yes I'm dealing with non standard customers. We moved from net47-owin to netcore-openidconnect and some how the content-type was not being validated on owin.
We need to support application/x-www-form-urlencoded (_EDIT: application/json)_ content-type while the customer is able to fix their code.

I'll try to see how hard is to move from openiddict 2.0 to openiddict 3.0
Thank you for the quick response!

**Comment by kevinchalet** [comment]
`application/x-www-form-urlencoded` is fully supported (and it's even the only content type allowed by the specification). ASOS 1.x/2.x, OpenIddict 1.x/2.x/3.x all use a similar check to ensure the `Content-Type` header is equal to `application/x-www-form-urlencoded`, so it's weird. Are you 100% sure your issue is not caused by something else? (a weird proxy?)

**Comment by gonzaloluna** [comment]
Sorry, the customer is sending application/json not application/x-www-form-urlencoded.

**Comment by kevinchalet** [comment]
Oh yeah, it makes much more sense in this case. You should be able to support that using the procedure I described. It should be trivial to implement by using `System.Text.Json` to deserialize the request payload.
