### ISSUE TITLE
Incorrect references?

### ISSUE THREAD

**Issue by Gillardo** [openiddict/openiddict-core#91]
Just updated using `dotnet restore` and now getting this error with version alpha2-0224

> Assembly 'AspNet.Security.OpenIdConnect.Server' with identity 'AspNet.Security.OpenIdConnect.Server, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' uses 'Microsoft.IdentityModel.Tokens, Version=5.0.0.611, Culture=neutral, PublicKeyToken=31bf3856ad364e35' which has a higher version than referenced assembly 'Microsoft.IdentityModel.Tokens' with identity 'Microsoft.IdentityModel.Tokens, Version=5.0.0.117, Culture=neutral, PublicKeyToken=31bf3856ad364e35'

**Comment by kevinchalet** [comment]
As announced on Gitter, OpenIddict was recently updated to use the RC2 "CI release" packages instead of the RC3 packages. We'll migrate to the final RC2 packages when they are available on NuGet.org.

I recommend removing the `aspnetcidev` feed from your NuGet.config file and using `aspnetcirelease` instead: https://www.myget.org/gallery/aspnetcirelease.

Any chance you could change it and wipe your `.nuget\packages` folder to see if it solves this issue?

I assume you're seeing this error in VS? Is it working fine with `dotnet run`?

**Comment by Gillardo** [comment]
Thank you, project now seems to build.  I have changed my feed in my project to point to the new myget url
