### ISSUE TITLE
How to use it with nhibernate?

### ISSUE THREAD

**Issue by lcetinapta** [openiddict/openiddict-core#943]
I am building an application by using NHibernate, and I don't see any samples on how to do it.
I only see that NHibernate stores were removed. Is NHibernate no longer supported?

**Comment by kevinchalet** [comment]
> Is NHibernate no longer supported?

I added NHibernate support for one of my clients in 2019, but they moved away from NHibernate and opted for Dapper shortly after that. Due to an extremely low demand, the NHibernate stores have never been officially released.

It's worth noting there was a bug with `Id` generation - possibly introduced in recent versions of NHibernate - which motivated me to remove them from the repository earlier this year.

**Comment by kevinchalet** [comment]
@lcetinapta if it's important for you or your company, I'm not opposed to bringing back the NHibernate stores. If so, please consider sponsoring the project, as there's some time to dedicate chasing the key generation bug and adding the recently added APIs to the stores.
