### ISSUE TITLE
default Identity Server question

### ISSUE THREAD

**Issue by shima20** [openiddict/openiddict-core#96]
I have an app using the JWT Bearer Authentication in the startup and in Configure Services I'm doing the below.  Is there a way to authenticate the username and password from a different provider (sidestepping the default identity configuration) but still use the claims etc from the default identity server provider after the username and password has been validated?

services.AddIdentity<ApplicationUser, IdentityRole>()
                .AddEntityFrameworkStores<ApplicationDbContext>()
                .AddDefaultTokenProviders()
                .AddOpenIddictCore<Application>(config => config.UseEntityFramework());

**Comment by kevinchalet** [comment]
I'm not sure to understand what you're trying to do. Any chance you could post more details?

**Comment by shima20** [comment]
Sorry, it's a bit confusing.  Basically I have a separate server that already has usernames and passwords stored and I would like to authenticate using that. But utilize the default identity server for the claims, roles.  So technically there's 2 databases.

**Comment by kevinchalet** [comment]
Interesting scenario. Since OpenIddict simply relies on Identity's `UserManager` to validate the user credentials, I'd simply create my own `UserManager`, override the `UserManager.VerifyPasswordAsync` method and replace the default user manager by the custom one in the DI container.

Overriding the default user manager is a pretty common scenario in Identity and I'm pretty sure there's some documentation about that. You should ping the ASP.NET team and ask them to point you to the right direction.

**Comment by shima20** [comment]
Thank you for the suggestion.  Not the best scenario as the other team does not want to manage the roles etc so they wanted to keep it separate.

**Comment by shima20** [comment]
@PinpointTownes Who might I contact on the ASP.NET team?

**Comment by kevinchalet** [comment]
You can open a ticket [there](https://github.com/aspnet/Identity/issues) and ping @HaoK, @rustd or @danroth27.

**Comment by shima20** [comment]
Thank you, I will do that and close this one...
